#!/usr/bin/env bash

################################################################################
# Secure Run — Full Pipeline + Steganographic PDF Post-Processing
#
# This script wraps the standard run.sh pipeline and additionally applies
# steganographic security techniques to all generated PDFs.
#
# Usage:
#   ./secure_run.sh                         # Full pipeline + steganography
#   ./secure_run.sh --project <name>        # Specific project
#   ./secure_run.sh --steganography-only    # Post-process existing PDFs only
#   ./secure_run.sh --help                  # Show help
#
# Before any work: installs uv if missing (same policy as pipeline mode), runs
#   uv sync --group steganography
# so QR/Code128 steganography deps are present (--help skips sync).
#
# The steganographic post-processing produces a second *_steganography.pdf
# for every PDF generated by the pipeline. The original PDFs are untouched.
################################################################################

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/scripts/bash_utils.sh"

# ── Defaults ─────────────────────────────────────────────────────────────

PROJECT_NAME=""
STEG_ONLY=false
PIPELINE_ARGS=""

# ── Argument parsing ─────────────────────────────────────────────────────

show_secure_help() {
    echo
    echo -e "${BOLD}🔒 SECURE RUN — Pipeline + Steganography${NC}"
    echo -e "${BLUE}────────────────────────────────────────────────────────────────${NC}"
    echo
    echo -e "${BOLD}USAGE${NC}"
    echo "  $0 [OPTIONS]"
    echo
    echo -e "${BOLD}OPTIONS${NC}"
    echo -e "  ${GREEN}--project <name>${NC}          Target project (default stego: all active projects)"
    echo -e "  ${GREEN}--steganography-only${NC}      Skip pipeline, only post-process existing PDFs"
    echo -e "  ${GREEN}--skip-infra${NC}              Skip infrastructure tests in pipeline"
    echo -e "  ${GREEN}--core-only${NC}               Core pipeline only (no LLM)"
    echo -e "  ${GREEN}--help, -h${NC}                Show this help"
    echo
    echo -e "${BOLD}EXAMPLES${NC}"
    echo "  $0                                  # Full pipeline + steganography"
    echo "  $0 --project cognitive_case_diagrams # Specific project"
    echo "  $0 --steganography-only              # Re-process existing PDFs"
    echo "  $0 --pipeline --core-only            # Non-interactive core pipeline + stego"
    echo
    echo -e "${BOLD}STEGANOGRAPHIC TECHNIQUES${NC}"
    echo "  • Diagonal watermark overlays         • QR code + Code128 barcode strips"
    echo "  • PDF metadata + XMP injection         • SHA-256/512 hash embedding"
    echo "  • Invisible text layers                • Document ID fingerprinting"
    echo "  • Optional AES-256 encryption          • Optional PDF password protection"
    echo
    echo -e "${BOLD}CONFIGURATION${NC}"
    echo "  Configure in project manuscript/config.yaml under 'steganography:' section"
    echo
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --help|-h)
            show_secure_help
            exit 0
            ;;
        --project)
            if [[ -z "${2:-}" ]]; then
                log_error "Missing project name after --project"
                exit 1
            fi
            PROJECT_NAME="$2"
            PIPELINE_ARGS="$PIPELINE_ARGS --project $2"
            shift 2
            ;;
        --steganography-only)
            STEG_ONLY=true
            shift
            ;;
        --skip-infra)
            PIPELINE_ARGS="$PIPELINE_ARGS --skip-infra"
            shift
            ;;
        --core-only)
            PIPELINE_ARGS="$PIPELINE_ARGS --core-only"
            shift
            ;;
        *)
            PIPELINE_ARGS="$PIPELINE_ARGS $1"
            shift
            ;;
    esac
done

# ── Environment: uv + venv + steganography dependency group ─────────────
if ! ensure_secure_run_environment; then
    exit 1
fi

# ── Step 1: Run the normal pipeline (unless --steganography-only) ────────

if [[ "$STEG_ONLY" != "true" ]]; then
    log_header "STEP 1/2: Running Core/Interactive Pipeline"
    
    export SECURE_RUN_ACTIVE=1
    if ! bash "$SCRIPT_DIR/run.sh" $PIPELINE_ARGS; then
        log_error "Pipeline failed — steganographic post-processing skipped"
        exit 1
    fi
    
    log_success "Pipeline section completed successfully"
    echo
fi

# ── Step 2: Steganographic post-processing ───────────────────────────────

log_header "STEP 2/2: Steganographic PDF Post-Processing"

# Build project list:
# - If --project was passed, process only that project.
# - Otherwise process all discovered active projects.
PROJECT_NAMES=()
if [[ -z "$PROJECT_NAME" ]]; then
    while IFS= read -r line; do
        [[ -n "$line" ]] && PROJECT_NAMES+=("$line")
    done < <($(get_python_cmd) -c "
import sys
from pathlib import Path
sys.path.insert(0, '$REPO_ROOT')
from infrastructure.project.discovery import discover_projects

for p in discover_projects(Path('$REPO_ROOT')):
    print(p.qualified_name)
" 2>/dev/null)
else
    PROJECT_NAMES=("$PROJECT_NAME")
fi

if [[ ${#PROJECT_NAMES[@]} -eq 0 ]]; then
    log_error "No projects found"
    exit 1
fi

log_info "Projects selected for steganography: ${PROJECT_NAMES[*]}"

overall_status=0
for selected_project in "${PROJECT_NAMES[@]}"; do
    log_info "Processing project: $selected_project"

    # Run steganographic post-processing via Python
    $(get_python_cmd) -c "
import sys
from pathlib import Path

sys.path.insert(0, '$REPO_ROOT')

from infrastructure.core.logging.utils import get_logger, setup_logger
from infrastructure.core.config.loader import load_config
from infrastructure.steganography import SteganographyProcessor, SteganographyConfig
from infrastructure.project.discovery import discover_projects

logger = get_logger('secure_run')

repo_root = Path('$REPO_ROOT')
project_name = '$selected_project'

projects = discover_projects(repo_root)
project_info = None
for p in projects:
    if p.qualified_name == project_name:
        project_info = p
        break

if project_info is None:
    logger.error('Unknown project: %s', project_name)
    sys.exit(1)

project_path = project_info.path

# Load steganography config from config.yaml
config_path = None
for candidate in [
    project_path / 'manuscript' / 'config.yaml',
    repo_root / 'project' / 'manuscript' / 'config.yaml',
]:
    if candidate.exists():
        config_path = candidate
        break

steg_config = SteganographyConfig.all_enabled()
title = project_name
authors = []
keywords = []

if config_path:
    import yaml
    with open(config_path) as f:
        raw = yaml.safe_load(f) or {}
    
    # Override with config.yaml steganography section if present
    if 'steganography' in raw:
        steg_config = SteganographyConfig.from_dict(raw['steganography'])
        steg_config.enabled = True  # secure_run always enables
    
    # Extract title and authors from config
    paper = raw.get('paper', {})
    title = paper.get('title', project_name)
    authors = [a.get('name', '') for a in raw.get('authors', [])]
    keywords = raw.get('keywords', [])

logger.info('Steganography config loaded (enabled=%s)', steg_config.enabled)

# Find all PDFs in the project output directory
pdf_dir = project_path / 'output' / 'pdf'
if not pdf_dir.exists():
    # Try root-level output
    pdf_dir = repo_root / 'output' / project_name

if not pdf_dir.exists():
    logger.warning('No PDF output directory found: %s', pdf_dir)
    sys.exit(0)

pdfs = list(pdf_dir.glob('*.pdf'))
# Exclude already-processed steganography files
pdfs = [p for p in pdfs if '_steganography' not in p.stem]

if not pdfs:
    logger.warning('No PDFs found in %s', pdf_dir)
    sys.exit(0)

logger.info('Found %d PDF(s) to process', len(pdfs))

processor = SteganographyProcessor(steg_config)
success_count = 0

for pdf_path in pdfs:
    try:
        result = processor.process(
            pdf_path,
            title=title,
            authors=authors,
            keywords=keywords,
        )
        logger.info('✓ %s → %s', pdf_path.name, result.name)
        success_count += 1
    except Exception as exc:
        logger.error('✗ Failed to process %s: %s', pdf_path.name, exc)

logger.info('Steganography complete: %d/%d PDFs processed', success_count, len(pdfs))
sys.exit(0 if success_count == len(pdfs) else 1)
"

    exit_code=$?

    if [[ $exit_code -eq 0 ]]; then
        log_success "Steganographic post-processing complete for $selected_project"

        # ── Mirror stego outputs to root output/{name}/pdf/ ──────────────
        # The pipeline's copy stage (05_copy_outputs.py) runs before steganography,
        # so we manually sync the new *_steganography.pdf and *.hashes.json files.
        ROOT_PDF_DIR="$SCRIPT_DIR/output/$selected_project/pdf"
        PROJECT_PDF_DIR="$SCRIPT_DIR/projects/$selected_project/output/pdf"

        if [[ -d "$ROOT_PDF_DIR" && -d "$PROJECT_PDF_DIR" ]]; then
            steg_count=0
            for f in "$PROJECT_PDF_DIR"/*_steganography.pdf "$PROJECT_PDF_DIR"/*.hashes.json; do
                [[ -f "$f" ]] || continue
                cp "$f" "$ROOT_PDF_DIR/"
                steg_count=$((steg_count + 1))
            done
            if [[ $steg_count -gt 0 ]]; then
                log_info "Mirrored $steg_count steganographic file(s) → output/$selected_project/pdf/"
            fi
        else
            log_info "Root output directory not found — skipping mirror (output/$selected_project/pdf/ may not exist yet)"
        fi
    else
        log_error "Steganographic post-processing failed for $selected_project (exit code: $exit_code)"
        overall_status=1
    fi

    echo
    echo -e "${BOLD}📁 Output locations for $selected_project:${NC}"
    echo -e "  Normal PDFs:             ${CYAN}projects/$selected_project/output/pdf/*.pdf${NC}"
    echo -e "  Steganography PDFs:      ${CYAN}projects/$selected_project/output/pdf/*_steganography.pdf${NC}"
    echo -e "  Hash manifests:          ${CYAN}projects/$selected_project/output/pdf/*.hashes.json${NC}"
    echo -e "  (also mirrored to)       ${CYAN}output/$selected_project/pdf/*_steganography.pdf${NC}"
    echo -e "  (also mirrored to)       ${CYAN}output/$selected_project/pdf/*.hashes.json${NC}"
done

if [[ $overall_status -eq 0 ]]; then
    log_success "Steganography finished for all selected projects"
fi

exit $overall_status
