"""Markdown and console formatting for test suite summary reports.

This module converts test summary data dictionaries into
human-readable Markdown and console output formats.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from infrastructure.core.logging.utils import get_logger

from .report_builder import generate_summary_report

logger = get_logger(__name__)


def generate_markdown_report(data: dict[str, Any]) -> str:
    """Generate human-readable markdown report from test data.

    Args:
        data: Test results dictionary

    Returns:
        Markdown formatted report
    """
    lines = []

    lines.append("# Full Repository Test Suite Results")
    lines.append("")
    lines.append(f"**Date**: {data['timestamp']}")
    lines.append(f"**Test Type**: {data['test_type']}")
    lines.append(f"**Overall Status**: {'PASSED' if data['overall_success'] else 'FAILED'}")
    lines.append("")

    # Summary section
    lines.append("## Summary")
    lines.append("")
    summary = data["summary"]
    lines.append(f"- **Total Tests**: {summary['total_tests']:,}")
    lines.append(f"- **Passed**: {summary['total_passed']:,}")
    lines.append(f"- **Failed**: {summary['total_failed']:,}")
    lines.append(f"- **Skipped**: {summary['total_skipped']:,}")
    lines.append(f"- **Pass Rate**: {summary['pass_rate']:.1f}%")
    lines.append(f"- **Weighted Coverage**: {summary['weighted_coverage_percent']:.1f}%")
    lines.append(f"- **Total Duration**: {summary['total_duration_seconds']:.1f}s")
    lines.append("")

    # Infrastructure results
    lines.append("## Infrastructure Tests")
    lines.append("")
    infra = data["infrastructure"]
    status = "PASSED" if infra["exit_code"] == 0 else "FAILED"
    lines.append(f"**Status**: {status}")
    lines.append(
        f"**Tests**: {infra['passed']:,} passed, {infra['failed']:,} failed, {infra['skipped']:,} skipped"  # noqa: E501
    )
    if infra["warnings"] > 0:
        lines.append(f"**Warnings**: {infra['warnings']:,}")
    lines.append(
        f"**Coverage**: {infra['coverage_percent']:.1f}% ({'meets' if infra['meets_threshold'] else 'below'} 60% threshold)"  # noqa: E501
    )
    lines.append(f"**Lines**: {infra['covered_lines']:,}/{infra['total_lines']:,} covered")
    lines.append(f"**Duration**: {infra['duration_seconds']:.1f}s")
    lines.append("")

    # Project results (dynamic)
    projects = data.get("projects", {})
    for project_name, proj_data in sorted(projects.items()):
        # Format project name for display (convert underscores to spaces, title case)
        display_name = project_name.replace("_", " ").title()
        lines.append(f"## {display_name} Tests")
        lines.append("")
        status = "PASSED" if proj_data["exit_code"] == 0 else "FAILED"
        lines.append(f"**Status**: {status}")
        lines.append(
            f"**Tests**: {proj_data['passed']:,} passed, {proj_data['failed']:,} failed, {proj_data['skipped']:,} skipped"  # noqa: E501
        )
        if proj_data["warnings"] > 0:
            lines.append(f"**Warnings**: {proj_data['warnings']:,}")
        lines.append(
            f"**Coverage**: {proj_data['coverage_percent']:.1f}% ({'meets' if proj_data['meets_threshold'] else 'below'} 90% threshold)"  # noqa: E501
        )
        lines.append(
            f"**Lines**: {proj_data['covered_lines']:,}/{proj_data['total_lines']:,} covered"
        )
        lines.append(f"**Duration**: {proj_data['duration_seconds']:.1f}s")
        lines.append("")

    # Metadata
    lines.append("## Test Configuration")
    lines.append("")
    meta = data["metadata"]
    lines.append(
        f"- **Infrastructure Tests**: {'Included' if meta['infrastructure_tests_included'] else 'Excluded'}"  # noqa: E501
    )
    lines.append(
        f"- **Integration Tests**: {'Included' if meta['integration_tests_included'] else 'Excluded'}"  # noqa: E501
    )
    lines.append(f"- **Slow Tests**: {'Included' if meta['slow_tests_included'] else 'Excluded'}")
    lines.append(
        f"- **Ollama Tests**: {'Included' if meta['ollama_tests_included'] else 'Excluded'}"
    )
    lines.append(
        f"- **Ollama Server**: {'Available' if meta['ollama_server_available'] else 'Unavailable'}"
    )
    if "active_projects" in meta:
        lines.append(f"- **Active Projects**: {', '.join(meta['active_projects'])}")
    lines.append("")

    # Files generated
    lines.append("## Generated Files")
    lines.append("")
    for file in data["files_generated"]:
        lines.append(f"- `{file}`")
    lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*Report generated by `scripts/generate_test_summary.py`*")

    return "\n".join(lines)


def _format_console_summary(report_data: dict[str, Any]) -> str:
    """Format a console-friendly summary string from report data."""
    summary = report_data["summary"]
    infra = report_data["infrastructure"]
    projects = report_data.get("projects", {})
    lines = [
        "",
        "=" * 80,
        "FULL REPOSITORY TEST SUITE SUMMARY",
        "=" * 80,
        f"Overall Status: {'PASSED' if report_data['overall_success'] else 'FAILED'}",
        f"Total Tests: {summary['total_tests']:,} ({summary['pass_rate']:.1f}% pass rate)",
        f"Total Duration: {summary['total_duration_seconds']:.1f}s",
        f"Weighted Coverage: {summary['weighted_coverage_percent']:.1f}%",
        "",
        "Suite Breakdown:",
        f"  Infrastructure:          {infra['passed']:,} passed ({infra['coverage_percent']:.1f}% coverage)",  # noqa: E501
    ]
    for project_name, proj_data in sorted(projects.items()):
        display_name = project_name[:20] + "..." if len(project_name) > 23 else project_name
        lines.append(
            f"  {display_name:<24} {proj_data['passed']:,} passed ({proj_data['coverage_percent']:.1f}% coverage)"  # noqa: E501
        )
    lines.append("=" * 80)
    return "\n".join(lines)


def run_test_summary_generation() -> int:
    """Main entry point for generating test summary reports."""
    logger.info("Generating comprehensive test summary reports...")

    # Generate the summary data
    report_data = generate_summary_report()

    # Save JSON report
    json_file = Path("test_results_summary.json")
    try:
        with open(json_file, "w") as f:
            json.dump(report_data, f, indent=2)
        logger.info(f"JSON report saved: {json_file}")
    except OSError as e:
        logger.error(f"Failed to write JSON report to {json_file}: {e}")
        raise

    # Generate and save markdown report
    markdown_content = generate_markdown_report(report_data)
    md_file = Path("test_results_summary.md")
    try:
        with open(md_file, "w") as f:
            f.write(markdown_content)
        logger.info(f"Markdown report saved: {md_file}")
    except OSError as e:
        logger.error(f"Failed to write markdown report to {md_file}: {e}")
        raise

    logger.info(_format_console_summary(report_data))

    return 0
