"""Real-data tests for ``infrastructure.documentation.architecture_overview``.

Zero-mock: builds tiny on-disk infrastructure / projects skeletons under
``tmp_path``, asserts the generated Mermaid is well-formed, and (when
``mmdc`` is available) renders it to SVG with the system Chrome.

If ``mmdc`` is not on ``PATH`` the renderer test skips gracefully — the
Mermaid-source tests still run.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
from pathlib import Path

import pytest

from infrastructure.documentation.architecture_overview import (
    architecture_overview_is_current,
    build_architecture_mermaid,
    render_architecture_svg,
)


def test_current_check_rejects_nonempty_stale_svg(tmp_path: Path) -> None:
    (tmp_path / "infrastructure" / "core").mkdir(parents=True)
    (tmp_path / "infrastructure" / "core" / "__init__.py").write_text("", encoding="utf-8")
    generated = tmp_path / "docs" / "_generated"
    generated.mkdir(parents=True)
    source = build_architecture_mermaid(tmp_path)
    (generated / "architecture_overview.mmd").write_text(source, encoding="utf-8")
    (generated / "architecture_overview.svg").write_text("<svg>stale but nonempty</svg>", encoding="utf-8")

    assert architecture_overview_is_current(tmp_path) is False


def _make_fake_repo(root: Path) -> None:
    """Build a minimal repo skeleton with one infra package + one project."""
    # Infrastructure Python package "foo"
    foo_pkg = root / "infrastructure" / "foo"
    foo_pkg.mkdir(parents=True)
    (foo_pkg / "__init__.py").write_text('"""foo infra package."""\n', encoding="utf-8")

    # Sibling Python package "bar" (so we test alphabetical ordering)
    bar_pkg = root / "infrastructure" / "bar"
    bar_pkg.mkdir(parents=True)
    (bar_pkg / "__init__.py").write_text('"""bar infra package."""\n', encoding="utf-8")

    # Non-Python config dir (no __init__.py)
    config_dir = root / "infrastructure" / "config_only"
    config_dir.mkdir(parents=True)
    (config_dir / "settings.yaml").write_text("k: v\n", encoding="utf-8")

    # Minimal valid public project under projects/templates/
    proj = root / "projects" / "templates" / "template_code_project"
    (proj / "src").mkdir(parents=True)
    (proj / "src" / "__init__.py").write_text("", encoding="utf-8")
    (proj / "src" / "demo.py").write_text("def hello() -> str:\n    return 'hi'\n", encoding="utf-8")
    (proj / "tests").mkdir(parents=True)
    (proj / "tests" / "__init__.py").write_text("", encoding="utf-8")


def test_build_architecture_mermaid_includes_foo_package(tmp_path: Path) -> None:
    """The Mermaid source must reference each infra package by name."""
    _make_fake_repo(tmp_path)

    src = build_architecture_mermaid(tmp_path)

    # Header + flowchart declaration
    assert src.startswith("%% Generated by infrastructure.documentation.architecture_overview")
    assert "flowchart TB" in src

    # Both infra packages appear (with the directory-relative label form)
    assert "infrastructure/foo/" in src
    assert "infrastructure/bar/" in src

    # Non-Python config dir lands in the config cluster
    assert "infrastructure/config_only/" in src

    # Public project is rendered
    assert "projects/templates/template_code_project/" in src

    # Cluster anchors and pipeline node are wired up
    assert 'Pipeline["Pipeline orchestrator' in src
    assert "InfraPy --> Pipeline" in src
    assert "InfraCfg --> Pipeline" in src
    assert "Pipeline --> Projects" in src


def test_build_architecture_mermaid_uses_double_quoted_labels(tmp_path: Path) -> None:
    """GitHub's parser requires double-quoted labels — no ``[/path/]`` syntax."""
    _make_fake_repo(tmp_path)

    src = build_architecture_mermaid(tmp_path)

    # Every node label line should look like   id["..."]   not   id[/.../]
    label_lines = [ln for ln in src.splitlines() if "infrastructure/" in ln or "projects/" in ln]
    assert label_lines, "expected at least one labelled node line"
    for ln in label_lines:
        # Skip subgraph header lines and edge lines (they don't define nodes)
        if "subgraph" in ln or "-->" in ln:
            continue
        assert re.search(r'\["[^"]+"\]', ln), f"node line is missing double-quoted label: {ln!r}"
        assert "[/" not in ln, f"parallelogram syntax leaked into node line: {ln!r}"


def test_build_architecture_mermaid_is_alphabetically_sorted(tmp_path: Path) -> None:
    """Determinism: packages must come out in alphabetical order."""
    _make_fake_repo(tmp_path)

    src = build_architecture_mermaid(tmp_path)
    bar_idx = src.index("infrastructure/bar/")
    foo_idx = src.index("infrastructure/foo/")
    assert bar_idx < foo_idx, "expected 'bar' to render before 'foo' (alphabetical)"


def test_build_architecture_mermaid_is_byte_deterministic(tmp_path: Path) -> None:
    _make_fake_repo(tmp_path)

    assert build_architecture_mermaid(tmp_path) == build_architecture_mermaid(tmp_path)


def test_build_architecture_mermaid_handles_empty_projects(tmp_path: Path) -> None:
    """Skeleton with no projects/ dir should still produce a valid diagram."""
    foo_pkg = tmp_path / "infrastructure" / "foo"
    foo_pkg.mkdir(parents=True)
    (foo_pkg / "__init__.py").write_text("", encoding="utf-8")

    src = build_architecture_mermaid(tmp_path)

    assert "flowchart TB" in src
    assert "infrastructure/foo/" in src
    # Falls back to a placeholder node so the cluster is never empty
    assert "no active projects discovered" in src


def test_render_architecture_svg_raises_when_mmdc_missing(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """If mmdc isn't on PATH the renderer must raise a clear RuntimeError."""
    _make_fake_repo(tmp_path)

    # Pre-flight: the .mmd is written before we look for mmdc, so we just need
    # to point PATH at an empty directory to simulate a missing binary.
    empty_bin = tmp_path / "empty_bin"
    empty_bin.mkdir()
    monkeypatch.setenv("PATH", str(empty_bin))

    with pytest.raises(RuntimeError, match="mmdc"):
        render_architecture_svg(tmp_path, tmp_path / "out" / "arch.svg")


@pytest.mark.timeout(60)  # real mmdc+Chromium render: ~4-8s, exceeds the 10s default under CI/dev load
@pytest.mark.skipif(shutil.which("mmdc") is None, reason="mmdc (mermaid-cli) not installed")
def test_render_architecture_svg_produces_valid_svg(tmp_path: Path) -> None:
    """End-to-end: mmdc renders our Mermaid source into a non-trivial SVG."""
    _make_fake_repo(tmp_path)

    out = tmp_path / "out" / "arch.svg"
    rendered = render_architecture_svg(tmp_path, out)

    assert rendered == out.resolve()
    assert out.is_file(), "mmdc should have written the SVG"
    svg_text = out.read_text(encoding="utf-8")
    assert svg_text.lstrip().startswith("<svg") or "<svg" in svg_text[:200]
    assert out.stat().st_size > 500, "SVG looks suspiciously small"

    # The .mmd source landed next to the SVG
    mmd_path = out.with_suffix(".mmd")
    assert mmd_path.is_file()
    assert "flowchart TB" in mmd_path.read_text(encoding="utf-8")


@pytest.mark.timeout(60)  # real mmdc+Chromium render: ~4-8s, exceeds the 10s default under CI/dev load
@pytest.mark.skipif(shutil.which("mmdc") is None, reason="mmdc (mermaid-cli) not installed")
def test_generated_mermaid_parses_via_mmdc(tmp_path: Path) -> None:
    """Sanity check: mmdc itself is willing to parse the generated source."""
    _make_fake_repo(tmp_path)

    src = build_architecture_mermaid(tmp_path)
    mmd_path = tmp_path / "diag.mmd"
    mmd_path.write_text(src, encoding="utf-8")
    out_path = tmp_path / "diag.svg"

    # Use the bundled puppeteer config approach so the test works on macOS
    # without requiring a separate Chromium download. mmdc errors via stderr.
    # Resolve a Chrome/Chromium executable across platforms:
    # 1. CHROME_EXECUTABLE_PATH env var (CI sets this)
    # 2. puppeteer's chrome-headless-shell cache
    # 3. macOS system Chrome
    chrome_env = os.environ.get("CHROME_EXECUTABLE_PATH", "")
    chrome_candidates = [
        chrome_env,
        str(
            Path.home()
            / ".cache"
            / "puppeteer"
            / "chrome-headless-shell"
            / "linux-150.0.7871.24"
            / "chrome-headless-shell-linux64"
            / "chrome-headless-shell"
        ),
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    ]
    chrome_path = next((p for p in chrome_candidates if p and Path(p).exists()), "")
    if not chrome_path:
        pytest.skip(
            "Chrome/Chromium not installed — set CHROME_EXECUTABLE_PATH or install puppeteer chrome-headless-shell"
        )

    puppeteer_cfg = tmp_path / "puppeteer.json"
    import json as _json

    puppeteer_cfg.write_text(
        _json.dumps({"executablePath": chrome_path, "args": ["--no-sandbox"]}),
        encoding="utf-8",
    )
    result = subprocess.run(  # noqa: S603 - test-only invocation with literal args
        [
            shutil.which("mmdc") or "mmdc",
            "-i",
            str(mmd_path),
            "-o",
            str(out_path),
            "-p",
            str(puppeteer_cfg),
            "-q",
        ],
        capture_output=True,
        text=True,
        check=False,
        timeout=45,
    )
    assert result.returncode == 0, f"mmdc rejected the source:\n{result.stderr}"
    assert out_path.is_file()
