"""Generated exemplar-roster differentiation map for the public template roster.

Builds ``docs/_generated/exemplar_roster.md`` from the single roster source of
truth (:data:`infrastructure.project.public_scope.PUBLIC_PROJECT_NAMES`) plus
each exemplar's own README and ``pyproject.toml``. The goal is a single,
regenerable "copy THIS template when…" table so differentiation guidance can
never silently rot in hand-maintained docs.

Contract enforced here (and by ``tests/infra_tests/project/test_exemplar_roster.py``):

- every public exemplar has a README with an H1 title;
- every public exemplar README carries a ``## When to use this template``
  section (temporary exceptions are pinned in :data:`KNOWN_MISSING_USE_WHEN`);
- the generated doc contains exactly one row per public exemplar.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from infrastructure.project.public_scope import PUBLIC_PROJECT_NAMES

USE_WHEN_HEADING = "## When to use this template"

# Exemplars temporarily allowed to lack the use-when section. Keep this empty
# unless a concurrent workstream owns the README (then pin it here with a date
# so the gap is tracked, not forgotten).
KNOWN_MISSING_USE_WHEN: tuple[str, ...] = (
    # Owned by the sheaf-integrity workstream (PR #23) as of 2026-06-10; add
    # the section there and remove this entry.
    "templates/template_active_inference",
)

DOC_RELATIVE_PATH = Path("docs/_generated/exemplar_roster.md")

_GENERATED_HEADER = (
    "# Public Exemplar Roster — Differentiation Map\n"
    "\n"
    "> Auto-generated by `scripts/generate_exemplar_roster_doc.py` from\n"
    "> `infrastructure.project.public_scope.PUBLIC_PROJECT_NAMES` and each\n"
    "> exemplar's README/pyproject. Do not edit manually — regenerate instead.\n"
)


@dataclass(frozen=True)
class ExemplarEntry:
    """One public exemplar's differentiation row."""

    name: str
    title: str
    use_when: str
    test_file_count: int
    coverage_floor: int | None

    @property
    def has_use_when(self) -> bool:
        return bool(self.use_when.strip())


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.is_file() else ""


def _extract_h1(readme_text: str) -> str:
    for line in readme_text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return ""


def _extract_use_when(readme_text: str) -> str:
    """Return the body of the use-when section, up to the next H2."""
    lines = readme_text.splitlines()
    collected: list[str] = []
    in_section = False
    for line in lines:
        if line.strip().lower() == USE_WHEN_HEADING.lower():
            in_section = True
            continue
        if in_section and line.startswith("## "):
            break
        if in_section:
            collected.append(line)
    return "\n".join(collected).strip()


def _first_sentence(text: str) -> str:
    flat = re.sub(r"\s+", " ", text).strip()
    # Drop markdown links' targets to keep table cells short: [text](url) -> text.
    flat = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", flat)
    match = re.search(r"(.+?\.)(\s|$)", flat)
    sentence = match.group(1) if match else flat
    return sentence.replace("|", "\\|")


def _coverage_floor(pyproject_text: str) -> int | None:
    # Anchored to line start so a commented-out historical knob can't shadow
    # the real one (Forge MINOR-1, 2026-06-10).
    match = re.search(r"^\s*fail_under\s*=\s*(\d+)", pyproject_text, re.MULTILINE)
    return int(match.group(1)) if match else None


def collect_entries(repo_root: Path) -> list[ExemplarEntry]:
    """Build one entry per public exemplar, in roster order."""
    entries: list[ExemplarEntry] = []
    for name in PUBLIC_PROJECT_NAMES:
        project_dir = repo_root / "projects" / name
        readme_text = _read_text(project_dir / "README.md")
        pyproject_text = _read_text(project_dir / "pyproject.toml")
        test_files = sorted((project_dir / "tests").rglob("test_*.py")) if (project_dir / "tests").is_dir() else []
        entries.append(
            ExemplarEntry(
                name=name,
                title=_extract_h1(readme_text),
                use_when=_extract_use_when(readme_text),
                test_file_count=len(test_files),
                coverage_floor=_coverage_floor(pyproject_text),
            )
        )
    return entries


def missing_use_when(entries: list[ExemplarEntry]) -> list[str]:
    """Names of exemplars whose README lacks the use-when section."""
    return [entry.name for entry in entries if not entry.has_use_when]


def unexpected_missing_use_when(entries: list[ExemplarEntry]) -> list[str]:
    """Missing use-when sections that are NOT pinned as known exceptions."""
    return [name for name in missing_use_when(entries) if name not in KNOWN_MISSING_USE_WHEN]


def render_roster_markdown(entries: list[ExemplarEntry]) -> str:
    rows = [
        "| Exemplar | Title | When to use | Test files | Coverage floor |",
        "| --- | --- | --- | ---: | ---: |",
    ]
    for entry in entries:
        use_when = (
            _first_sentence(entry.use_when)
            if entry.has_use_when
            else "*(not yet documented — see KNOWN_MISSING_USE_WHEN)*"
        )
        floor = f"{entry.coverage_floor}%" if entry.coverage_floor is not None else "—"
        title = entry.title.replace("|", "\\|")
        rows.append(
            f"| [`{entry.name}`](../../projects/{entry.name}/README.md) "
            f"| {title} "
            f"| {use_when} "
            f"| {entry.test_file_count} "
            f"| {floor} |"
        )
    table = "\n".join(rows)
    return (
        f"{_GENERATED_HEADER}\n"
        f"{table}\n"
        "\n"
        "Each exemplar's README carries the full `## When to use this template`\n"
        "section; this table shows the first sentence only. Counts here are\n"
        "static (test *files*); authoritative measured coverage lives in\n"
        "[`canonical_facts.md`](canonical_facts.md).\n"
    )


def write_roster_doc(repo_root: Path, out_path: Path | None = None) -> Path:
    """Render and write the roster doc; returns the written path."""
    target = out_path if out_path is not None else repo_root / DOC_RELATIVE_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_roster_markdown(collect_entries(repo_root)), encoding="utf-8")
    return target
