"""Command-line interface for literature search.

Subcommands:

* ``search`` — run a query against the configured backends and emit JSON
  on stdout (or a file). Backends default to ``arxiv,crossref``; pass
  ``--source local --corpus path/to/corpus.json`` for offline use, or
  ``--source paperclip`` if ``PAPERCLIP_API_KEY`` is set.
* ``to-bibtex`` — same as ``search``, but emit BibTeX directly using the
  citation module.

The CLI never raises on per-backend failures; it surfaces them as a
``"errors"`` field in the JSON output (or as a ``%`` comment block above the
BibTeX output) so agents can detect partial coverage.
"""

import argparse
import os
import sys
from pathlib import Path

from infrastructure.core.logging.utils import get_logger
from infrastructure.search.literature.backends import (
    ArxivBackend,
    CrossrefBackend,
    LocalBackend,
    PaperclipBackend,
    SearchBackend,
)
from infrastructure.search.literature.cache import SearchCache
from infrastructure.search.literature.client import LiteratureClient
from infrastructure.search.literature.models import SearchQuery

logger = get_logger(__name__)


def _build_backends(args: argparse.Namespace) -> list[SearchBackend]:
    sources = [s.strip() for s in args.source.split(",") if s.strip()]
    backends: list[SearchBackend] = []
    for source in sources:
        if source == "arxiv":
            backends.append(ArxivBackend())
        elif source == "crossref":
            backends.append(CrossrefBackend(mailto=args.mailto))
        elif source == "local":
            if not args.corpus:
                raise SystemExit("--source local requires --corpus PATH")
            backends.append(LocalBackend(args.corpus))
        elif source == "paperclip":
            api_key = os.environ.get("PAPERCLIP_API_KEY", "")
            if not api_key:
                raise SystemExit("--source paperclip requires PAPERCLIP_API_KEY environment variable")
            backends.append(PaperclipBackend(api_key=api_key))
        else:
            raise SystemExit(f"Unknown source: {source!r}")
    return backends


def _build_query(args: argparse.Namespace) -> SearchQuery:
    return SearchQuery(
        text=args.query,
        max_results=args.max_results,
        year_min=args.from_year,
        year_max=args.to_year,
    )


def _build_client(args: argparse.Namespace) -> LiteratureClient:
    backends = _build_backends(args)
    cache: SearchCache | None = None
    if args.cache_dir:
        cache = SearchCache(args.cache_dir, ttl_seconds=args.cache_ttl)
    return LiteratureClient(backends, cache=cache)


def _cmd_search(args: argparse.Namespace) -> int:
    client = _build_client(args)
    query = _build_query(args)
    result = client.search(query, use_cache=not args.no_cache)
    output = result.to_json(indent=2)
    if args.output == "-" or not args.output:
        sys.stdout.write(output)
        sys.stdout.write("\n")
    else:
        Path(args.output).write_text(output + "\n", encoding="utf-8")
        logger.info(
            "Wrote %d papers from %d backends → %s",
            len(result),
            len(result.per_source_counts),
            args.output,
        )
    return 0 if not result.errors or args.tolerate_errors else 1


def _cmd_to_bibtex(args: argparse.Namespace) -> int:
    # Local imports keep the search module importable when reference
    # is unavailable (e.g. mid-refactor).
    from infrastructure.reference.citation import paper_to_bibentry, render_database
    from infrastructure.reference.citation.models import BibDatabase

    client = _build_client(args)
    query = _build_query(args)
    result = client.search(query, use_cache=not args.no_cache)

    db = BibDatabase()
    if result.errors:
        notes = "\n".join(f"  {src}: {msg}" for src, msg in result.errors.items())
        db.preamble = (
            "Auto-generated by infrastructure.search.literature\n"
            f"Query: {query.text!r}\n"
            f"Partial coverage — backend errors:\n{notes}"
        )
    for paper in result.papers:
        db.add(paper_to_bibentry(paper))

    bibtex = render_database(db)
    if args.output == "-" or not args.output:
        sys.stdout.write(bibtex)
    else:
        Path(args.output).write_text(bibtex, encoding="utf-8")
        logger.info("Wrote %d entries → %s", len(db), args.output)
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python -m infrastructure.search.literature",
        description="Aggregated literature search across arXiv, Crossref, Paperclip, and local corpora.",
    )

    def add_common(p: argparse.ArgumentParser) -> None:
        p.add_argument("query", help="Search query string")
        p.add_argument("--max-results", "-n", type=int, default=10)
        p.add_argument("--from-year", type=int, default=None, dest="from_year")
        p.add_argument("--to-year", type=int, default=None, dest="to_year")
        p.add_argument(
            "--source",
            default="arxiv,crossref",
            help="Comma-separated backend names (arxiv,crossref,local,paperclip)",
        )
        p.add_argument(
            "--corpus",
            default=None,
            help="Path to JSON corpus (required for --source local)",
        )
        p.add_argument(
            "--mailto",
            default=None,
            help="Email passed to Crossref for polite-pool routing",
        )
        p.add_argument("--cache-dir", default=None, help="Enable on-disk cache")
        p.add_argument(
            "--cache-ttl",
            type=int,
            default=None,
            help="Cache TTL in seconds (default: no expiry)",
        )
        p.add_argument(
            "--no-cache",
            action="store_true",
            help="Bypass cache reads (still writes results back)",
        )
        p.add_argument("--output", "-o", default="-", help="Output path or '-' for stdout")

    sub = parser.add_subparsers(dest="command", required=True)

    p_search = sub.add_parser("search", help="Run a query and emit JSON.")
    add_common(p_search)
    p_search.add_argument(
        "--tolerate-errors",
        action="store_true",
        help="Exit 0 even when one or more backends report errors.",
    )
    p_search.set_defaults(func=_cmd_search)

    p_bib = sub.add_parser("to-bibtex", help="Run a query and emit BibTeX.")
    add_common(p_bib)
    p_bib.set_defaults(func=_cmd_to_bibtex)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return int(args.func(args))


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
