"""Generated publication-identity blocks for exemplar standalone guides."""

from __future__ import annotations

import re
from typing import Protocol

STANDALONE_BLOCK_BEGIN = "<!-- BEGIN:PUBLICATION_INDEX -->"
STANDALONE_BLOCK_END = "<!-- END:PUBLICATION_INDEX -->"


class StandalonePublicationRecord(Protocol):
    """Minimal publication record surface required by the standalone renderer."""

    project_name: str
    paper_version: str
    concept_doi: str
    version_doi: str
    version_record: str
    published_artifacts: tuple[tuple[str, str], ...]

    @property
    def github_display_label(self) -> str:
        """Human-readable label for the GitHub repository link."""
        ...

    @property
    def github_display_url(self) -> str:
        """Absolute HTTPS URL of the GitHub repository."""
        ...


def _link(label: str, url: str) -> str:
    return f"[{label}]({url})" if url else "n/a"


def render_standalone_publication_block(record: StandalonePublicationRecord) -> str:
    """Render a deterministic, source-owned publication identity block."""
    concept = _link(record.concept_doi, f"https://doi.org/{record.concept_doi}" if record.concept_doi else "")
    version = _link(record.version_doi, record.version_record)
    repository = _link(record.github_display_label, record.github_display_url)
    extra = (
        ", ".join(_link(platform, url) for platform, url in record.published_artifacts)
        if record.published_artifacts
        else "none declared"
    )
    return "\n".join(
        [
            STANDALONE_BLOCK_BEGIN,
            "<!-- Generated by scripts/docgen/publication_records.py; do not hand-edit. -->",
            "",
            "## Publication identity",
            "",
            f"- Standalone repository: {repository}",
            f"- Config version: `{record.paper_version or 'n/a'}`",
            f"- Stable concept DOI: {concept}",
            f"- Latest deposited version DOI: {version}",
            f"- Additional declared locations: {extra}",
            "- Metadata source: [`manuscript/config.yaml`](manuscript/config.yaml); citation sidecars live at the "
            "project root.",
            "",
            "Additional locations are config-declared publication evidence; the central index records whether external "
            "GitHub and Zenodo checks were refreshed.",
            "",
            STANDALONE_BLOCK_END,
        ]
    )


def replace_standalone_publication_block(text: str, block: str) -> str:
    """Replace the generated block, or insert it immediately after the H1."""
    pattern = re.compile(
        re.escape(STANDALONE_BLOCK_BEGIN) + r".*?" + re.escape(STANDALONE_BLOCK_END),
        flags=re.DOTALL,
    )
    if pattern.search(text):
        return pattern.sub(block, text)
    lines = text.splitlines()
    heading_index = next((index for index, line in enumerate(lines) if line.startswith("# ")), None)
    if heading_index is None:
        raise ValueError("Standalone guide has no H1 for publication-index insertion")
    lines[heading_index + 1 : heading_index + 1] = ["", block]
    return "\n".join(lines).rstrip() + "\n"


def extract_standalone_publication_block(text: str) -> str:
    """Return the generated block, or an empty string when markers are absent."""
    match = re.search(
        re.escape(STANDALONE_BLOCK_BEGIN) + r".*?" + re.escape(STANDALONE_BLOCK_END),
        text,
        flags=re.DOTALL,
    )
    return match.group(0) if match else ""
