"""Plaintext abstract rendering for Zenodo and GitHub release metadata."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from infrastructure.core.logging.utils import get_logger
from infrastructure.prose.markdown import normalise_for_deposit
from infrastructure.publishing.zenodo_urls import zenodo_record_url_from_doi
from infrastructure.rendering.manuscript_injection import substitute_manuscript_text

logger = get_logger(__name__)

__all__ = [
    "DepositCrossLinks",
    "build_deposit_description",
    "build_github_release_body",
    "github_release_url",
    "render_abstract_plaintext",
    "resolve_abstract_source",
    "resolve_variables_path",
    "zenodo_record_url_from_doi",
]

_ABSTRACT_FILENAME = "00_abstract.md"


@dataclass(frozen=True)
class DepositCrossLinks:
    """Cross-platform identifiers appended to deposit descriptions."""

    project: str
    tag: str
    github_repo: str
    pdf_sha256: str
    doi: str | None = None
    zenodo_record_url: str | None = None
    github_release_url: str | None = None
    release_name: str | None = None


def github_release_url(github_repo: str, tag: str) -> str:
    """Return the canonical GitHub release URL for a repository tag."""
    return f"https://github.com/{github_repo}/releases/tag/{tag}"


def resolve_abstract_source(
    repo_root: Path,
    project_name: str,
    *,
    manuscript_abstract: Path,
) -> Path:
    """Prefer hydrated ``output/manuscript/00_abstract.md`` when present."""
    hydrated = repo_root / "projects" / project_name / "output" / "manuscript" / _ABSTRACT_FILENAME
    if hydrated.is_file():
        return hydrated
    project_hydrated = repo_root / "output" / project_name / "manuscript" / _ABSTRACT_FILENAME
    if project_hydrated.is_file():
        return project_hydrated
    return manuscript_abstract


def resolve_variables_path(repo_root: Path, project_name: str) -> Path | None:
    """Return manuscript variables JSON when generated by the analysis stage."""
    candidates = [
        repo_root / "projects" / project_name / "output" / "data" / "manuscript_variables.json",
        repo_root / "output" / project_name / "data" / "manuscript_variables.json",
    ]
    for path in candidates:
        if path.is_file():
            return path
    return None


def load_manuscript_variables(variables_path: Path | None) -> dict[str, str]:
    """Load ``{{TOKEN}}`` substitution values from JSON."""
    if variables_path is None or not variables_path.is_file():
        return {}
    try:
        payload = json.loads(variables_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        logger.warning("Could not read manuscript variables from %s: %s", variables_path, exc)
        return {}
    if not isinstance(payload, dict):
        return {}
    return {str(key): str(value) for key, value in payload.items()}


def render_abstract_plaintext(
    abstract_source: Path,
    *,
    variables_path: Path | None = None,
    override_text: str | None = None,
    max_len: int | None = None,
) -> str:
    """Render a deposit-safe plaintext abstract from markdown or override text."""
    if override_text is not None and override_text.strip():
        body = override_text.strip()
    else:
        try:
            raw = abstract_source.read_text(encoding="utf-8")
        except OSError as exc:
            logger.warning("Could not read abstract from %s: %s", abstract_source, exc)
            return ""
        variables = load_manuscript_variables(variables_path)
        if variables:
            raw, unresolved = substitute_manuscript_text(raw, variables)
            if unresolved:
                logger.warning(
                    "Unresolved manuscript tokens in %s: %s",
                    abstract_source.name,
                    ", ".join(sorted(set(unresolved))),
                )
        body = normalise_for_deposit(raw)

    if max_len is not None and len(body) > max_len:
        return body[:max_len].rstrip() + "..."
    return body


def format_cross_links_footer(cross_links: DepositCrossLinks) -> str:
    """Build a plaintext footer block for cross-platform artifact linkage."""
    lines = ["---", "Associated artifacts"]
    gh_url = cross_links.github_release_url or github_release_url(
        cross_links.github_repo,
        cross_links.tag,
    )
    gh_label = cross_links.release_name or cross_links.tag
    lines.append(f"GitHub release: {gh_label} ({gh_url})")
    if cross_links.doi:
        lines.append(f"DOI: https://doi.org/{cross_links.doi}")
    if cross_links.zenodo_record_url:
        lines.append(f"Zenodo: {cross_links.zenodo_record_url}")
    lines.append(f"PDF SHA-256: {cross_links.pdf_sha256}")
    return "\n".join(lines)


def build_deposit_description(
    *,
    abstract_source: Path,
    variables_path: Path | None,
    cross_links: DepositCrossLinks,
    override_text: str | None = None,
    max_len: int | None = None,
) -> str:
    """Build the full Zenodo deposit description with cross-link footer."""
    body = render_abstract_plaintext(
        abstract_source,
        variables_path=variables_path,
        override_text=override_text,
        max_len=max_len,
    )
    footer = format_cross_links_footer(cross_links)
    if not body:
        return footer
    return f"{body}\n\n{footer}"


def build_github_release_body(
    *,
    project_name: str,
    tag: str,
    abstract_plaintext: str,
    doi: str | None,
    pdf_sha256: str,
    zenodo_record_url: str | None = None,
    github_release_url: str | None = None,
    version: str | None = None,
) -> str:
    """Build a structured GitHub release description with publication metadata."""
    lines = [
        f"Release {tag} for {project_name}.",
        "",
        "## Publication",
    ]
    if version:
        lines.append(f"- Version: {version}")
    if github_release_url:
        lines.append(f"- GitHub release: {github_release_url}")
    if doi:
        lines.append(f"- DOI: https://doi.org/{doi}")
    if zenodo_record_url:
        lines.append(f"- Zenodo: {zenodo_record_url}")
    lines.append(f"- PDF SHA-256: `{pdf_sha256}`")
    if abstract_plaintext:
        lines.extend(["", "## Abstract", abstract_plaintext])
    return "\n".join(lines)
