"""Executable bundle assembly for opt-in Stage 10."""

from __future__ import annotations

import hashlib
import json
import shutil
import sys
from pathlib import Path
from typing import Any

import yaml

from infrastructure.core.logging.utils import get_logger
from infrastructure.project.public_scope import PUBLIC_PROJECT_NAMES
from infrastructure.rendering.dockerfile_gen import (
    DockerfileConfig,
    build_compose_yaml,
    build_dockerfile,
)
from infrastructure.rendering.manifest import build_manifest

logger = get_logger(__name__)

_COMBINED_PDF_SUFFIX = "_combined.pdf"


def _resolve_combined_pdf(repo_root: Path, project_name: str, project_dir: Path) -> Path | None:
    """Return the first existing combined PDF path, or ``None`` if not built yet."""
    project_slug = Path(project_name).name
    candidates = (
        repo_root / "output" / project_name / "pdf" / f"{project_slug}{_COMBINED_PDF_SUFFIX}",
        project_dir / "output" / "pdf" / f"{project_slug}{_COMBINED_PDF_SUFFIX}",
    )
    for path in candidates:
        if path.is_symlink():
            raise ValueError(f"executable bundle refuses symlinked PDF artifact: {path}")
        if path.is_file():
            return path
    return None


def _load_publication_doi(project_dir: Path) -> str | None:
    """Read ``publication.doi`` from ``manuscript/config.yaml`` when present."""
    config_path = project_dir / "manuscript" / "config.yaml"
    if not config_path.is_file():
        return None
    raw: Any = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    if not isinstance(raw, dict):
        return None
    publication = raw.get("publication")
    if not isinstance(publication, dict):
        return None
    doi = publication.get("doi")
    if doi is None:
        return None
    doi_text = str(doi).strip()
    return doi_text or None


def _copy_pdf_artifact(
    repo_root: Path,
    project_name: str,
    project_dir: Path,
    output_dir: Path,
) -> Path | None:
    """Copy the combined PDF into ``artifacts/pdf/`` when a pipeline output exists."""
    pdf_src = _resolve_combined_pdf(repo_root, project_name, project_dir)
    if pdf_src is None:
        logger.warning(
            "Combined PDF not found for %s — bundle will omit artifacts/pdf/ (run the render stage first).",
            project_name,
        )
        return None
    pdf_dst_dir = output_dir / "artifacts" / "pdf"
    pdf_dst_dir.mkdir(parents=True, exist_ok=True)
    pdf_dst = pdf_dst_dir / pdf_src.name
    shutil.copy2(pdf_src, pdf_dst)
    logger.info("Copied combined PDF to %s", pdf_dst)
    return pdf_dst


def _write_bundle_readme(output_dir: Path, project_name: str, *, pdf_copied: bool) -> None:
    display_name = Path(project_name).name
    pdf_section = (
        "## Delivered PDF\n\n"
        f"The rendered manuscript snapshot lives at "
        f"``artifacts/pdf/{display_name}{_COMBINED_PDF_SUFFIX}``.\n\n"
        if pdf_copied
        else "## Delivered PDF\n\n"
        "No combined PDF was bundled — run the render stage before Stage 10 "
        "to include ``artifacts/pdf/``.\n\n"
    )
    reproduce_section = (
        "## Reproduce\n\n"
        "The bundled Dockerfile copies project ``source/`` only. Full pipeline "
        "reproduction still requires this template repository root "
        "(``infrastructure/``, root ``scripts/``, and ``uv.lock``).\n\n"
        "```\n"
        "docker compose run reproduce\n"
        "```\n"
    )
    (output_dir / "README.md").write_text(
        f"# Executable Bundle — {project_name}\n\n"
        f"Auto-generated by `scripts/runner/bundle_executable.py`. See "
        f"`manifest.json` for the canonical entry-point and claims, "
        f"`docs/maintenance/stage-10-executable-bundle.md` for design rationale.\n\n"
        f"{pdf_section}"
        f"{reproduce_section}",
        encoding="utf-8",
    )


def bundle_project(
    repo_root: Path,
    project_name: str,
    *,
    python_version: str = "3.12",
) -> Path:
    """Build executable bundle under output/<project>/executable_bundle/."""
    repo_root = repo_root.resolve()
    if project_name not in PUBLIC_PROJECT_NAMES:
        raise ValueError(f"executable bundles are limited to canonical public projects: {project_name}")
    project_dir = repo_root / "projects" / project_name
    if not project_dir.exists():
        logger.warning(
            "Project directory not found: %s — skipping bundle (exit code 2 = graceful skip).",
            project_dir,
        )
        sys.exit(2)
    _reject_symlinks(project_dir)

    output_dir = repo_root / "output" / project_name / "executable_bundle"
    _reject_symlink_components(repo_root, output_dir)
    if output_dir.is_symlink():
        raise ValueError(f"refusing to replace symlinked bundle output: {output_dir}")
    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    project_slug = Path(project_name).name
    pinned_path = repo_root / "tests" / "regression" / "pinned_values" / f"{project_slug}.json"
    publication_doi = _load_publication_doi(project_dir)
    archival_receipts: dict[str, str] = {}
    if publication_doi:
        archival_receipts["zenodo_doi"] = publication_doi
    manifest = build_manifest(
        project_name=project_name,
        repo_dir=repo_root,
        pinned_values_path=pinned_path,
        archival_receipts=archival_receipts or None,
    )
    manifest.write_to(output_dir / "manifest.json")
    logger.info("Wrote manifest.json with %d claims", len(manifest.claims))

    dockerfile_text = build_dockerfile(DockerfileConfig(project_name=project_name, python_version=python_version))
    (output_dir / "Dockerfile").write_text(dockerfile_text, encoding="utf-8")
    (output_dir / "docker-compose.yml").write_text(
        build_compose_yaml(project_name),
        encoding="utf-8",
    )

    lockfile_src = repo_root / "uv.lock"
    pyproject_src = repo_root / "pyproject.toml"
    if not lockfile_src.is_file() or not pyproject_src.is_file():
        raise ValueError("executable bundle requires both root uv.lock and pyproject.toml")
    lockfile_dst = output_dir / "lockfile"
    lockfile_dst.mkdir(parents=True, exist_ok=True)
    shutil.copy2(lockfile_src, lockfile_dst / "uv.lock")
    shutil.copy2(pyproject_src, lockfile_dst / "pyproject.toml")
    shutil.copy2(lockfile_src, output_dir / "uv.lock")
    shutil.copy2(pyproject_src, output_dir / "pyproject.toml")

    source_dst = output_dir / "source"
    if source_dst.exists():
        shutil.rmtree(source_dst)
    source_dst.mkdir(parents=True, exist_ok=True)
    for sub in ("src", "scripts", "manuscript", "tests"):
        sub_src = project_dir / sub
        if sub_src.exists():
            shutil.copytree(sub_src, source_dst / sub, dirs_exist_ok=True)

    pdf_dst = _copy_pdf_artifact(repo_root, project_name, project_dir, output_dir)
    _write_bundle_readme(output_dir, project_name, pdf_copied=pdf_dst is not None)
    _write_bundle_receipt(output_dir)
    return output_dir


def _reject_symlinks(root: Path) -> None:
    """Reject source trees containing symlinks before copying them."""
    for path in (root, *root.rglob("*")):
        if path.is_symlink():
            raise ValueError(f"executable bundle refuses symlinked source: {path}")


def _reject_symlink_components(root: Path, candidate: Path) -> None:
    """Reject symlinked parent components before bundle cleanup/copying."""
    root = root.resolve()
    try:
        relative = candidate.relative_to(root)
    except ValueError as exc:
        raise ValueError(f"executable bundle path escapes repository root: {candidate}") from exc
    current = root
    for component in relative.parts:
        current = current / component
        if current.is_symlink():
            raise ValueError(f"executable bundle path contains symlink component: {current}")


def _write_bundle_receipt(output_dir: Path) -> None:
    """Write an immutable file manifest after bundle assembly."""
    entries: list[dict[str, object]] = []
    for path in sorted(output_dir.rglob("*")):
        if not path.is_file() or path.name == "bundle_receipt.json":
            continue
        if path.is_symlink():
            raise ValueError(f"executable bundle contains symlinked payload: {path}")
        content = path.read_bytes()
        entries.append(
            {
                "path": path.relative_to(output_dir).as_posix(),
                "bytes": len(content),
                "sha256": hashlib.sha256(content).hexdigest(),
            }
        )
    payload = {
        "schema_version": "template-executable-bundle/v2",
        "file_count": len(entries),
        "files": entries,
    }
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    payload["manifest_sha256"] = hashlib.sha256(canonical).hexdigest()
    (output_dir / "bundle_receipt.json").write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
