"""Compile all-platform publishing metadata + status into a README markdown block.

This is the single place that turns the publishing **registry** (the source of
truth for *which* platforms exist) plus a project's ``manuscript/config.yaml``
(the source of truth for *what has been published*) into a compact, regenerable
Markdown block suitable for a project README.

Design contract
---------------
* The committed README status reflects **durable publication state** — DOIs,
  repository, and release identifiers recorded in ``config.yaml``. It never
  encodes machine-specific credential presence: whether a token happens to be
  in someone's local ``.env`` is volatile and not reproducible, so it must not
  leak into a public, version-controlled README. Live credential verification
  is a separate, opt-in concern (see ``credential_check.py``).
* The block is delimited by stable HTML-comment markers so it can be rewritten
  deterministically without disturbing surrounding prose.
* Platform rows are generated from :data:`registry.PLATFORM_REGISTRY`, so adding
  a platform to the registry automatically surfaces it here.

Public API
----------
* :func:`compile_publishing_status` — build a :class:`PublishingStatusReport`.
* :func:`render_status_markdown` — render the inner Markdown (no markers).
* :func:`render_status_block` — render the marker-wrapped block.
* :func:`update_readme_block` — replace the block inside README text.
* :func:`status_report_is_current` — check whether a README block is up to date.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Mapping

import yaml

from infrastructure.publishing.config_doi import (
    read_publication_doi,
    read_publication_version_doi,
    zenodo_record_url_for_doi,
)
from infrastructure.publishing.registry import (
    PLATFORM_REGISTRY,
    PlatformInfo,
    PublishingTier,
)

BLOCK_START = "<!-- PUBLISHING-STATUS:START (generated by infrastructure.publishing.status_report) -->"
BLOCK_END = "<!-- PUBLISHING-STATUS:END -->"

_STATE_BADGE = {
    "published": "✅ published",
    "reserved": "🔵 reserved",
    "available": "⚪ available",
    "planned": "🟡 planned",
}


class PublicationState(str, Enum):
    """Durable publication state of an artifact on a given platform."""

    PUBLISHED = "published"  # a durable identifier exists (DOI, repo, release, CID)
    RESERVED = "reserved"
    AVAILABLE = "available"  # adapter implemented + locally verifiable, not yet published here
    PLANNED = "planned"  # documented intent only, no live adapter


@dataclass(frozen=True)
class PlatformStatus:
    """Per-platform status row."""

    name: str
    tier: str
    state: PublicationState
    description: str
    reference: str | None
    reference_label: str | None
    env_vars: tuple[str, ...]


@dataclass(frozen=True)
class PublishingStatusReport:
    """Aggregated publishing metadata + per-platform status for one project."""

    title: str
    version: str | None
    authors: tuple[str, ...]
    license: str | None
    keywords: tuple[str, ...]
    concept_doi: str | None
    version_doi: str | None
    version_record: str | None
    github_repo: str | None
    repository_url: str | None
    platforms: tuple[PlatformStatus, ...] = field(default_factory=tuple)

    @property
    def published_count(self) -> int:
        """Return the count of published items."""
        return sum(1 for p in self.platforms if p.state is PublicationState.PUBLISHED)


def _config_path_for(project_root: Path, config_path: Path | None) -> Path:
    return config_path or (project_root / "manuscript" / "config.yaml")


def _load_config(config_path: Path) -> dict[str, Any]:
    if not config_path.exists():
        return {}
    data = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    return data if isinstance(data, dict) else {}


def _author_names(config: Mapping[str, Any]) -> tuple[str, ...]:
    authors = config.get("authors") or []
    names: list[str] = []
    for entry in authors:
        if isinstance(entry, Mapping) and entry.get("name"):
            names.append(str(entry["name"]).strip())
        elif isinstance(entry, str) and entry.strip():
            names.append(entry.strip())
    return tuple(names)


def _platform_state(
    platform: PlatformInfo,
    *,
    concept_doi: str | None,
    doi_status: str | None,
    github_repo: str | None,
    repository_url: str | None,
    published: Mapping[str, str],
) -> tuple[PublicationState, str | None, str | None]:
    """Resolve (state, reference_url, reference_label) for one platform.

    ``published`` is an optional caller-supplied map of platform name -> reference
    URL for artifacts published outside ``config.yaml`` (e.g. an IPFS CID or a
    HuggingFace dataset URL recorded in an upload receipt). It only ever upgrades
    a platform to PUBLISHED; it never downgrades.
    """
    # Explicit caller-recorded publication wins.
    override = published.get(platform.name)
    if override:
        return PublicationState.PUBLISHED, override, override

    if platform.name == "zenodo" and concept_doi:
        state = PublicationState.RESERVED if _doi_is_reserved(doi_status) else PublicationState.PUBLISHED
        return (
            state,
            f"https://doi.org/{concept_doi}",
            concept_doi,
        )
    if platform.name == "github" and github_repo:
        url = repository_url or f"https://github.com/{github_repo}"
        return PublicationState.PUBLISHED, url, github_repo
    if platform.name == "github_pages" and github_repo:
        # Pages availability is durable once a repo exists, but the deployed URL
        # is not recorded in config, so keep it "available" with the repo as ref.
        return PublicationState.AVAILABLE, repository_url, github_repo

    if platform.tier is PublishingTier.DOCUMENTED:
        return PublicationState.PLANNED, None, None
    return PublicationState.AVAILABLE, None, None


def _doi_is_reserved(doi_status: str | None) -> bool:
    normalized = (doi_status or "").strip().lower()
    return "reserved" in normalized and "published" not in normalized


def compile_publishing_status(
    project_root: Path,
    *,
    config_path: Path | None = None,
    published: Mapping[str, str] | None = None,
) -> PublishingStatusReport:
    """Aggregate publishing metadata + per-platform status for a project.

    Args:
        project_root: Project directory (containing ``manuscript/config.yaml``).
        config_path: Explicit config path override.
        published: Optional map of platform-name -> reference URL for artifacts
            published outside config (used to upgrade rows to PUBLISHED).

    Returns:
        A :class:`PublishingStatusReport`.
    """
    cfg_path = _config_path_for(project_root, config_path)
    config = _load_config(cfg_path)

    paper = config.get("paper") or {}
    publication = config.get("publication") or {}
    metadata = config.get("metadata") or {}

    # Durable published references from config, overridable by the caller param.
    config_published = publication.get("published_artifacts") or {}
    merged_published: dict[str, str] = {}
    if isinstance(config_published, Mapping):
        merged_published.update({str(k): str(v) for k, v in config_published.items() if v})
    merged_published.update(dict(published or {}))
    published = merged_published

    concept_doi = read_publication_doi(cfg_path)
    version_doi = read_publication_version_doi(cfg_path)
    doi_status = (publication.get("doi_status") or "").strip() or None
    version_record = (publication.get("version_record") or "").strip() or None
    if version_doi and not version_record:
        try:
            version_record = zenodo_record_url_for_doi(version_doi)
        except Exception:  # noqa: BLE001 — a malformed DOI just means no record link
            version_record = None

    github_repo = (publication.get("github_repository") or "").strip() or None
    repository_url = (publication.get("repository_url") or "").strip() or None

    rows: list[PlatformStatus] = []
    for platform in PLATFORM_REGISTRY:
        state, ref, label = _platform_state(
            platform,
            concept_doi=concept_doi,
            doi_status=doi_status,
            github_repo=github_repo,
            repository_url=repository_url,
            published=published,
        )
        rows.append(
            PlatformStatus(
                name=platform.name,
                tier=platform.tier.value,
                state=state,
                description=platform.description,
                reference=ref,
                reference_label=label,
                env_vars=platform.env_vars,
            )
        )

    keywords = tuple(str(k).strip() for k in (config.get("keywords") or []) if str(k).strip())

    return PublishingStatusReport(
        title=str(paper.get("title") or project_root.name),
        version=(str(paper.get("version")).strip() if paper.get("version") else None),
        authors=_author_names(config),
        license=(str(metadata.get("license")).strip() if metadata.get("license") else None),
        keywords=keywords,
        concept_doi=concept_doi,
        version_doi=version_doi,
        version_record=version_record,
        github_repo=github_repo,
        repository_url=repository_url,
        platforms=tuple(rows),
    )


def _md_link(label: str | None, url: str | None) -> str:
    if url and label:
        return f"[{label}]({url})"
    if url:
        return f"<{url}>"
    return "—"


def render_status_markdown(report: PublishingStatusReport) -> str:
    """Render the inner Markdown for the status block (without markers)."""
    lines: list[str] = []

    # Metadata header line.
    meta_bits: list[str] = [f"**{report.title}**"]
    if report.version:
        meta_bits.append(f"v{report.version}")
    if report.license:
        meta_bits.append(report.license)
    if report.authors:
        meta_bits.append(", ".join(report.authors))
    lines.append(" · ".join(meta_bits))
    lines.append("")

    # Identifier line.
    id_bits: list[str] = []
    if report.concept_doi:
        id_bits.append(f"Concept DOI: {_md_link(report.concept_doi, f'https://doi.org/{report.concept_doi}')}")
    if report.version_doi:
        id_bits.append(
            f"Version DOI: {_md_link(report.version_doi, report.version_record or f'https://doi.org/{report.version_doi}')}"
        )
    if report.github_repo:
        id_bits.append(f"Repository: {_md_link(report.github_repo, report.repository_url)}")
    if id_bits:
        lines.append(" | ".join(id_bits))
        lines.append("")

    # Platform status table.
    published = report.published_count
    lines.append(f"Publishing surface — {len(report.platforms)} platforms, {published} published:")
    lines.append("")
    lines.append("| Platform | Tier | Status | Reference | Credentials |")
    lines.append("| --- | --- | --- | --- | --- |")
    for p in report.platforms:
        badge = _STATE_BADGE[p.state.value]
        ref = _md_link(p.reference_label, p.reference)
        creds = ", ".join(f"`{e}`" for e in p.env_vars) if p.env_vars else "—"
        tier = p.tier.replace("_", "-")
        lines.append(f"| {p.name} | {tier} | {badge} | {ref} | {creds} |")
    lines.append("")

    if report.keywords:
        lines.append(f"_Keywords: {', '.join(report.keywords)}._")
        lines.append("")

    lines.append(
        "_Status legend: ✅ published (durable identifier recorded in `config.yaml`) · "
        "🔵 reserved (identifier reserved but not yet registered by final publication) · "
        "⚪ available (adapter implemented and locally verifiable) · 🟡 planned. "
        "This block is generated — edit `manuscript/config.yaml`, then regenerate with "
        "`uv run python -m infrastructure.publishing.status_report --project <path> --write`._"
    )
    return "\n".join(lines)


def render_status_block(report: PublishingStatusReport) -> str:
    """Render the full marker-wrapped block."""
    return f"{BLOCK_START}\n{render_status_markdown(report)}\n{BLOCK_END}"


def update_readme_block(
    readme_text: str,
    report: PublishingStatusReport,
    *,
    init_after_heading: str | None = None,
) -> tuple[str, bool]:
    """Replace (or insert) the status block in README text.

    Args:
        readme_text: Current README contents.
        report: Compiled status report to render.
        init_after_heading: When markers are absent, insert the block immediately
            after the first line equal to this heading (e.g.
            ``"## Publication and rendering"``). If None and markers are absent,
            raises ValueError.

    Returns:
        ``(new_text, changed)``.
    """
    block = render_status_block(report)

    if BLOCK_START in readme_text and BLOCK_END in readme_text:
        start = readme_text.index(BLOCK_START)
        end = readme_text.index(BLOCK_END) + len(BLOCK_END)
        new_text = readme_text[:start] + block + readme_text[end:]
        return new_text, new_text != readme_text

    if init_after_heading is None:
        raise ValueError(
            "Status block markers not found and no init_after_heading given. "
            f"Add the markers manually or pass a heading to insert after.\n{BLOCK_START}\n...\n{BLOCK_END}"
        )

    lines = readme_text.splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.strip() == init_after_heading.strip():
            insert_at = i + 1
            prefix = "" if (insert_at < len(lines) and lines[insert_at].strip() == "") else "\n"
            lines.insert(insert_at, f"{prefix}\n{block}\n")
            new_text = "".join(lines)
            return new_text, True
    raise ValueError(f"Heading not found for block insertion: {init_after_heading!r}")


def status_report_is_current(readme_text: str, report: PublishingStatusReport) -> bool:
    """Return True when the README's status block matches the compiled report."""
    block = render_status_block(report)
    return block in readme_text


def _parse_published(pairs: list[str] | None) -> dict[str, str]:
    out: dict[str, str] = {}
    for item in pairs or []:
        name, _, url = item.partition("=")
        if name.strip() and url.strip():
            out[name.strip()] = url.strip()
    return out


def main(argv: list[str] | None = None) -> int:
    """CLI: compile and (optionally) write a README publishing-status block."""
    import argparse

    parser = argparse.ArgumentParser(
        prog="python -m infrastructure.publishing.status_report",
        description="Compile all-platform publishing metadata + status into a README block.",
    )
    parser.add_argument("--project", required=True, type=Path, help="Project root directory")
    parser.add_argument("--config", type=Path, default=None, help="Override manuscript/config.yaml path")
    parser.add_argument("--readme", type=Path, default=None, help="README path (default: <project>/README.md)")
    parser.add_argument("--write", action="store_true", help="Write the block into the README")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the README block is missing or stale (no write)",
    )
    parser.add_argument(
        "--init-after",
        default=None,
        help='Heading to insert the block after on first write, e.g. "## Publication and rendering"',
    )
    parser.add_argument(
        "--published",
        nargs="*",
        default=None,
        metavar="name=url",
        help="Mark platforms published with a reference URL (e.g. ipfs_pinata=https://...)",
    )
    args = parser.parse_args(argv)

    report = compile_publishing_status(
        args.project,
        config_path=args.config,
        published=_parse_published(args.published),
    )
    readme_path = args.readme or (args.project / "README.md")

    if args.check:
        text = readme_path.read_text(encoding="utf-8") if readme_path.exists() else ""
        if status_report_is_current(text, report):
            print(f"OK: publishing-status block is current in {readme_path}")
            return 0
        print(f"STALE: publishing-status block in {readme_path} is missing or out of date.")
        print("Regenerate with: --write")
        return 1

    if not args.write:
        print(render_status_block(report))
        return 0

    text = readme_path.read_text(encoding="utf-8") if readme_path.exists() else ""
    new_text, changed = update_readme_block(text, report, init_after_heading=args.init_after)
    if changed:
        readme_path.write_text(new_text, encoding="utf-8")
        print(f"Updated publishing-status block in {readme_path}")
    else:
        print(f"No change: publishing-status block already current in {readme_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
