"""Compose flat manuscript markdown from sheaf section manifests."""

from manuscript.sheaf.compose import (
    compose_all_sections,
    compose_section,
    issues_have_errors,
    validate_manifest,
)
from manuscript.sheaf.coverage import (
    SheafCoverageContext,
    build_coverage_matrix,
    classify_cell,
    coverage_matrix_to_dict,
    emit_coverage_artifacts,
    gray_cell_count,
    gray_cell_count_from_json,
    load_coverage_json,
    load_sheaf_coverage_context,
    validate_coverage_json_data,
    validate_coverage_strict,
    write_coverage_json,
)
from manuscript.sheaf.manifest import default_manifest_path, load_manifest, parse_missing
from manuscript.sheaf.models import (
    DEFAULT_MANIFEST_REL,
    DEFAULT_REGISTRY_REL,
    COVERAGE_COLORS,
    ComposeOptions,
    ComposeResult,
    CoverageCell,
    CoverageMatrix,
    CoverageSectionRow,
    ImradBlock,
    ManifestIssue,
    MissingTrackPolicy,
    SectionKind,
    SheafDefaults,
    SheafManifest,
    SheafSection,
    TrackRegistry,
    TrackSpec,
    coverage_cell_symbol,
)
from manuscript.sheaf.registry import list_registered_tracks, load_track_registry, track_order_for_section
from manuscript.sheaf.renderers import GENERATED_RENDERERS, RENDERERS, render_track_body, resolve_track_body
from manuscript.sheaf.report import (
    build_coverage_report,
    load_coverage_config,
    render_report_markdown,
    write_coverage_page,
)

# Backward-compatible alias for tests importing private helper.
_parse_missing = parse_missing

__all__ = [
    "COVERAGE_COLORS",
    "DEFAULT_MANIFEST_REL",
    "DEFAULT_REGISTRY_REL",
    "GENERATED_RENDERERS",
    "RENDERERS",
    "ComposeOptions",
    "ComposeResult",
    "CoverageCell",
    "CoverageMatrix",
    "CoverageSectionRow",
    "ImradBlock",
    "SectionKind",
    "MissingTrackPolicy",
    "SheafCoverageContext",
    "SheafDefaults",
    "SheafManifest",
    "SheafSection",
    "TrackRegistry",
    "TrackSpec",
    "_parse_missing",
    "build_coverage_report",
    "build_coverage_matrix",
    "classify_cell",
    "compose_all_sections",
    "compose_section",
    "coverage_cell_symbol",
    "coverage_matrix_to_dict",
    "emit_coverage_artifacts",
    "gray_cell_count",
    "gray_cell_count_from_json",
    "issues_have_errors",
    "list_registered_tracks",
    "load_coverage_config",
    "load_coverage_json",
    "load_sheaf_coverage_context",
    "load_manifest",
    "load_track_registry",
    "parse_missing",
    "render_report_markdown",
    "render_track_body",
    "resolve_track_body",
    "track_order_for_section",
    "validate_coverage_json_data",
    "validate_coverage_strict",
    "validate_manifest",
    "write_coverage_json",
    "write_coverage_page",
]
