#!/usr/bin/env python3
"""Executable-bundle stage orchestrator (Stage 10 — opt-in via [bundle] tag).

Thin orchestrator that:

1. Reads project name from --project
2. Builds the executable-bundle manifest from tests/regression/pinned_values/<project>.json
3. Generates a Dockerfile + docker-compose.yml
4. Snapshots the lockfile (uv.lock) + project source into output/<project>/executable_bundle/
5. Writes manifest.json
6. Reports the bundle path to stdout

This stage is OPT-IN — it does not run as part of the default core pipeline.
Enable via:

    ./run.sh --pipeline --project <name> --tags bundle

or run standalone:

    uv run python scripts/08_executable_bundle.py --project <name>

Exit codes:
    0: Bundle created successfully
    1: Bundle creation failed
    2: Project not found (graceful skip — pipeline executor allows skip when this is returned)

Design: ``docs/maintenance/stage-10-executable-bundle.md``.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from scripts import ensure_repo_root_on_path  # noqa: E402

ensure_repo_root_on_path()

from infrastructure.core.logging.utils import get_logger, log_header, log_success  # noqa: E402
from infrastructure.rendering.dockerfile_gen import (  # noqa: E402
    DockerfileConfig,
    build_compose_yaml,
    build_dockerfile,
)
from infrastructure.rendering.manifest import build_manifest  # noqa: E402

logger = get_logger(__name__)


def _bundle_project(repo_root: Path, project_name: str, python_version: str) -> Path:
    project_dir = repo_root / "projects" / project_name
    if not project_dir.exists():
        logger.warning(
            "Project directory not found: %s — skipping bundle (exit code 2 = graceful skip).",
            project_dir,
        )
        sys.exit(2)

    output_dir = repo_root / "output" / project_name / "executable_bundle"
    output_dir.mkdir(parents=True, exist_ok=True)

    # 1. Manifest
    pinned_path = repo_root / "tests" / "regression" / "pinned_values" / f"{project_name}.json"
    manifest = build_manifest(
        project_name=project_name,
        repo_dir=repo_root,
        pinned_values_path=pinned_path,
    )
    manifest.write_to(output_dir / "manifest.json")
    logger.info("Wrote manifest.json with %d claims", len(manifest.claims))

    # 2. Dockerfile + compose
    dockerfile_text = build_dockerfile(
        DockerfileConfig(project_name=project_name, python_version=python_version)
    )
    (output_dir / "Dockerfile").write_text(dockerfile_text, encoding="utf-8")
    (output_dir / "docker-compose.yml").write_text(
        build_compose_yaml(project_name), encoding="utf-8"
    )

    # 3. Snapshot lockfile + source
    lockfile_src = repo_root / "uv.lock"
    if lockfile_src.exists():
        lockfile_dst = output_dir / "lockfile"
        lockfile_dst.mkdir(parents=True, exist_ok=True)
        shutil.copy2(lockfile_src, lockfile_dst / "uv.lock")
        pyproject_src = repo_root / "pyproject.toml"
        if pyproject_src.exists():
            shutil.copy2(pyproject_src, lockfile_dst / "pyproject.toml")

    source_dst = output_dir / "source"
    if source_dst.exists():
        shutil.rmtree(source_dst)
    source_dst.mkdir(parents=True, exist_ok=True)
    for sub in ("src", "scripts", "manuscript", "tests"):
        sub_src = project_dir / sub
        if sub_src.exists():
            shutil.copytree(sub_src, source_dst / sub, dirs_exist_ok=True)

    # 4. README
    (output_dir / "README.md").write_text(
        f"# Executable Bundle — {project_name}\n\n"
        f"Auto-generated by `scripts/08_executable_bundle.py`. See "
        f"`manifest.json` for the canonical entry-point and claims, "
        f"`docs/maintenance/stage-10-executable-bundle.md` for design rationale.\n\n"
        f"## Reproduce\n\n"
        f"```\n"
        f"docker compose run reproduce\n"
        f"```\n",
        encoding="utf-8",
    )

    return output_dir


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build a project's executable bundle.")
    parser.add_argument("--project", required=True, help="Project name under projects/")
    parser.add_argument(
        "--python-version",
        default="3.12",
        help="Python version tag for the Dockerfile base (default: 3.12)",
    )
    args = parser.parse_args(argv)

    repo_root = Path(__file__).resolve().parent.parent
    log_header(f"Stage: Executable Bundle (project: {args.project})")

    output_dir = _bundle_project(repo_root, args.project, args.python_version)
    log_success(f"Bundle written to: {output_dir}")
    print(str(output_dir))
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
