"""Content building and formatting for LLM review outputs.

Builds markdown content for review headers, combined reviews, and metadata.
"""

from __future__ import annotations

from pathlib import Path

from infrastructure.llm.core.config import OllamaClientConfig
from infrastructure.llm.review.metrics import ReviewMetrics, SessionMetrics
from infrastructure.llm.review.review_analysis import (
    calculate_format_compliance_summary,
    calculate_quality_summary,
    extract_action_items,
)
from infrastructure.llm.templates import TRANSLATION_LANGUAGES
from infrastructure.llm.validation.format import check_format_compliance


def _build_review_header(name: str, model_name: str, date_str: str, metrics: ReviewMetrics) -> str:
    """Build the standard markdown header for a single review file."""
    return f"""# {name.replace("_", " ").title()}

*Generated by LLM ({model_name}) on {date_str}*
*Output: {metrics.output_chars:,} chars ({metrics.output_words:,} words) in {metrics.generation_time_seconds:.1f}s*

---

"""


def _build_combined_review_content(
    reviews: dict[str, str],
    model_name: str,
    pdf_path: Path,
    session_metrics: SessionMetrics,
    timestamp: str,
    date_str: str,
) -> str:
    """Build the combined review markdown content.

    Args:
        reviews: Dictionary of review name -> content
        model_name: Name of LLM model used
        pdf_path: Path to source manuscript PDF
        session_metrics: Complete session metrics
        timestamp: ISO timestamp string
        date_str: Date portion of timestamp (YYYY-MM-DD)

    Returns:
        Combined markdown content string
    """
    action_items = extract_action_items(reviews)
    quality_summary = calculate_quality_summary(reviews)
    format_compliance_summary = calculate_format_compliance_summary(reviews)

    # Build metrics summary
    metrics_summary = f"""## Generation Metrics

**Input Manuscript:**
- Characters: {session_metrics.manuscript.total_chars:,}
- Words: {session_metrics.manuscript.total_words:,}
- Estimated tokens: ~{session_metrics.manuscript.total_tokens_est:,}
- Truncated: {"Yes" if session_metrics.manuscript.truncated else "No"}

**Reviews Generated:**
"""
    for name, metrics in session_metrics.reviews.items():
        metrics_summary += f"- {name.replace('_', ' ').title()}: {metrics.output_chars:,} chars ({metrics.output_words:,} words) in {metrics.generation_time_seconds:.1f}s\n"  # noqa: E501

    metrics_summary += (
        f"\n**Total Generation Time:** {session_metrics.total_generation_time:.1f}s\n"
    )

    # Build navigation table
    nav_rows = [
        "| [Action Items](#action-items-checklist) | Prioritized TODO list |",
        "| [Executive Summary](#executive-summary) | Key findings overview |",
        "| [Quality Review](#quality-review) | Writing quality assessment |",
        "| [Methodology Review](#methodology-review) | Methods evaluation |",
        "| [Improvement Suggestions](#improvement-suggestions) | Detailed recommendations |",
    ]

    translation_keys = [k for k in reviews.keys() if k.startswith("translation_")]
    for trans_key in translation_keys:
        lang_code = trans_key.replace("translation_", "")
        lang_name = TRANSLATION_LANGUAGES.get(lang_code, lang_code)
        nav_rows.append(
            f"| [Translation ({lang_name})](#translation-{lang_code}) | Technical abstract in {lang_name} |"  # noqa: E501
        )

    nav_rows.append("| [Generation Metrics](#generation-metrics) | Review statistics |")
    nav_table = "\n".join(nav_rows)

    # Build translations section
    translations_section = ""
    if translation_keys:
        translations_section = "\n---\n\n# Translations\n\n"
        for trans_key in translation_keys:
            lang_code = trans_key.replace("translation_", "")
            lang_name = TRANSLATION_LANGUAGES.get(lang_code, lang_code)
            translations_section += f"""## Translation ({lang_name}) {{#translation-{lang_code}}}

{reviews.get(trans_key, "*Not generated*")}

---

"""

    return f"""# LLM Manuscript Review

*Generated by {model_name} on {date_str}*
*Source: {pdf_path.name}*

---

## Quick Navigation

| Section | Description |
|---------|-------------|
{nav_table}

---

## Quality Overview

{quality_summary}

{format_compliance_summary}

---

## Action Items Checklist

The following items are extracted from the review for easy tracking:

{action_items}

---

{metrics_summary}

---

# Executive Summary

{reviews.get("executive_summary", "*Not generated*")}

---

# Quality Review

{reviews.get("quality_review", "*Not generated*")}

---

# Methodology Review

{reviews.get("methodology_review", "*Not generated*")}

---

# Improvement Suggestions

{reviews.get("improvement_suggestions", "*Not generated*")}
{translations_section}---

## Review Metadata

- **Model:** {model_name}
- **Generated:** {timestamp}
- **Source:** {pdf_path.name}
- **Total Words Generated:** {sum(m.output_words for m in session_metrics.reviews.values()):,}

---

*End of LLM Manuscript Review*
"""


def _build_review_metadata(
    reviews: dict[str, str],
    model_name: str,
    pdf_path: Path,
    session_metrics: SessionMetrics,
    timestamp: str,
) -> dict:
    """Build the review metadata dictionary.

    Args:
        reviews: Dictionary of review name -> content
        model_name: Name of LLM model used
        pdf_path: Path to source manuscript PDF
        session_metrics: Complete session metrics
        timestamp: ISO timestamp string

    Returns:
        Metadata dictionary ready for JSON serialization
    """
    reviews_metrics_dict = {
        name: {
            "input_chars": m.input_chars,
            "input_words": m.input_words,
            "input_tokens_est": m.input_tokens_est,
            "output_chars": m.output_chars,
            "output_words": m.output_words,
            "output_tokens_est": m.output_tokens_est,
            "generation_time_seconds": round(m.generation_time_seconds, 2),
        }
        for name, m in session_metrics.reviews.items()
    }

    format_compliance_per_review = {}
    for name, content in reviews.items():
        is_compliant, issues, details = check_format_compliance(content)
        format_compliance_per_review[name] = {
            "compliant": is_compliant,
            "issues": issues,
            "conversational_phrases": len(details.get("conversational_phrases", [])),
        }

    total_reviews = len(reviews)
    compliant_reviews = sum(1 for r in format_compliance_per_review.values() if r["compliant"])
    compliance_rate = (compliant_reviews / total_reviews * 100) if total_reviews > 0 else 100

    llm_config = OllamaClientConfig.from_env()
    return {
        "model": model_name,
        "timestamp": timestamp,
        "source_pdf": str(pdf_path),
        "reviews_generated": list(reviews.keys()),
        "max_input_length": llm_config.max_input_length,
        "manuscript_metrics": {
            "total_chars": session_metrics.manuscript.total_chars,
            "total_words": session_metrics.manuscript.total_words,
            "total_tokens_est": session_metrics.manuscript.total_tokens_est,
            "truncated": session_metrics.manuscript.truncated,
            "truncated_chars": session_metrics.manuscript.truncated_chars,
        },
        "review_metrics": reviews_metrics_dict,
        "format_compliance": {
            "overall_rate": round(compliance_rate, 1),
            "compliant_reviews": compliant_reviews,
            "total_reviews": total_reviews,
            "per_review": format_compliance_per_review,
        },
        "total_generation_time_seconds": round(session_metrics.total_generation_time, 2),
        "config": {
            "temperature_summary": 0.3,
            "temperature_review": 0.3,  # quality_review
            "temperature_methodology": 0.3,  # same as quality: structured factual analysis
            "temperature_suggestions": 0.4,  # higher: creative ideation benefits from diversity
            "max_tokens": llm_config.long_max_tokens,
            "max_tokens_source": "long_max_tokens",
            "timeout_seconds": llm_config.review_timeout,
            "system_prompt": "manuscript_review",
        },
    }
