"""Rendering pipeline summary and verification utilities.

This module provides:
- Rendering output summary generation
- Summary logging with formatted output
- PDF output verification with quality checks
- Citation detection in manuscript files
"""

import re
import zipfile
from pathlib import Path
from typing import Any

import yaml

from infrastructure.core.logging.constants import BANNER_WIDTH
from infrastructure.core.logging.utils import get_logger, log_success
from infrastructure.core.project_paths import resolve_source_manuscript_dir
from infrastructure.publishing.transmission_bookends import is_transmission_bookend
from infrastructure.rendering._epub_package_validation import validate_epub_package
from infrastructure.rendering._pdf_latex_validation import validate_pdf_structure
from infrastructure.rendering.config import RenderingConfig
from infrastructure.rendering.latex_log_quality import (
    collect_latex_log_findings,
    format_latex_findings,
)
from infrastructure.rendering.manuscript_discovery import discover_manuscript_files
from infrastructure.project.discovery import resolve_project_root

logger = get_logger(__name__)


def _manuscript_dir_for_verify(project_root: Path) -> Path:
    """Prefer the populated injected copy, else the canonical source manuscript."""
    injected = project_root / "output" / "manuscript"
    if injected.exists() and any(injected.glob("*.md")):
        return injected
    return resolve_source_manuscript_dir(project_root)


def _strict_latex_warning_policy_enabled(project_root: Path, manuscript_dir: Path) -> bool:
    """Return whether this project fails render verification on log warnings."""
    candidates = [
        manuscript_dir / "config.yaml",
        resolve_source_manuscript_dir(project_root) / "config.yaml",
    ]
    for config_path in candidates:
        if not config_path.is_file():
            continue
        try:
            config = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
        except (OSError, yaml.YAMLError) as exc:
            logger.warning("Could not read render warning policy from %s: %s", config_path, exc)
            continue
        if not isinstance(config, dict):
            continue
        rendering = config.get("rendering", {})
        if isinstance(rendering, dict):
            return bool(rendering.get("fail_on_latex_warnings", False))
    return False


def _latex_log_files(project_root: Path) -> list[Path]:
    """Return combined-PDF and slide log files generated by the render stage."""
    pdf_log = project_root / "output" / "pdf" / "_combined_manuscript.log"
    slide_logs = sorted((project_root / "output" / "slides").glob("*_slides.log"))
    return [path for path in [pdf_log, *slide_logs] if path.exists()]


def _verify_latex_warning_policy(project_root: Path, manuscript_dir: Path) -> bool:
    """Apply the opt-in strict LaTeX warning policy for reviewer artifacts."""
    if not _strict_latex_warning_policy_enabled(project_root, manuscript_dir):
        return True

    log_files = _latex_log_files(project_root)
    if not log_files:
        logger.error("Strict LaTeX warning policy is enabled, but no render logs were found")
        return False

    findings = collect_latex_log_findings(log_files)
    if findings:
        logger.error("\n❌ Strict LaTeX warning policy failed")
        logger.error(format_latex_findings(findings))
        return False

    logger.info("✅ Strict LaTeX warning policy passed: %d log file(s) clean", len(log_files))
    return True


def generate_rendering_summary(project_name: str = "project", *, repo_root: Path | None = None) -> dict[str, Any]:
    """Generate comprehensive summary of rendering results.

    STABILITY: this is the canonical per-project rendering reporting surface.
    Tests may assert on substring presence (e.g. ``"RENDERING RESULTS SUMMARY"``,
    ``"Combined Manuscript PDF"``, ``"Web Outputs"``, ``"Presentation Slides"``).
    New sections may be appended; existing section headers MUST NOT change.

    See docs/operational/logging/output-design.md for the schema.

    Returns:
        Dictionary with rendering statistics and file information
    """
    root = repo_root or Path(__file__).parent.parent.parent
    project_root = resolve_project_root(root, project_name)
    output_dir = project_root / "output"

    summary: dict[str, Any] = {
        "project": project_name,
        "individual_pdfs": [],
        "combined_pdf": None,
        "combined_html": None,
        "web_outputs": [],
        "slides": [],
        "total_size_kb": 0,
    }

    project_basename = Path(project_name).name

    pdf_dir = output_dir / "pdf"
    if pdf_dir.exists():
        for pdf in sorted(pdf_dir.glob("*.pdf")):
            if pdf.name != f"{project_basename}_combined.pdf":
                size_kb = pdf.stat().st_size / 1024
                summary["individual_pdfs"].append({"name": pdf.name, "size_kb": size_kb})
                summary["total_size_kb"] += size_kb

    combined_pdf = pdf_dir / f"{project_basename}_combined.pdf"
    if combined_pdf.exists():
        size_kb = combined_pdf.stat().st_size / 1024
        summary["combined_pdf"] = {
            "name": combined_pdf.name,
            "size_kb": size_kb,
            "path": str(combined_pdf),
        }
        summary["total_size_kb"] += size_kb

    web_dir = output_dir / "web"
    if web_dir.exists():
        combined_html = web_dir / "index.html"
        if combined_html.exists():
            size_kb = combined_html.stat().st_size / 1024
            summary["combined_html"] = {
                "name": combined_html.name,
                "size_kb": size_kb,
                "path": str(combined_html),
            }
            summary["total_size_kb"] += size_kb

    if web_dir.exists():
        for html in sorted(web_dir.glob("*.html")):
            if html.name != "index.html":
                size_kb = html.stat().st_size / 1024
                summary["web_outputs"].append({"name": html.name, "size_kb": size_kb})

    slides_dir = output_dir / "slides"
    if slides_dir.exists():
        for slide in sorted(slides_dir.glob("*.pdf")):
            size_kb = slide.stat().st_size / 1024
            summary["slides"].append({"name": slide.name, "size_kb": size_kb})

    return summary


def log_rendering_summary(summary: dict[str, Any]) -> None:
    """Log comprehensive rendering summary with formatted output.

    STABILITY: this is the canonical per-project rendering reporting surface.
    Tests may assert on substring presence (e.g. ``"RENDERING RESULTS SUMMARY"``,
    ``"Combined Manuscript PDF"``, ``"Web Outputs"``, ``"Presentation Slides"``).
    New sections may be appended; existing section headers MUST NOT change.

    See docs/operational/logging/output-design.md for the schema.
    """
    logger.info("\n" + "=" * BANNER_WIDTH)
    logger.info("RENDERING RESULTS SUMMARY")
    logger.info("=" * BANNER_WIDTH)
    logger.info(f"Project: {summary['project']}")

    if summary["combined_pdf"]:
        pdf = summary["combined_pdf"]
        logger.info("\n📕 Combined Manuscript PDF:")
        logger.info(f"   {pdf['name']:<40} {pdf['size_kb']:>8.1f} KB")
        logger.info(f"   Location: {pdf['path']}")

    if summary["combined_html"]:
        html = summary["combined_html"]
        logger.info("\n🌐 Combined Manuscript HTML:")
        logger.info(f"   {html['name']:<40} {html['size_kb']:>8.1f} KB")
        logger.info(f"   Location: {html['path']}")

    if summary["individual_pdfs"]:
        logger.info(f"\n📄 Individual Section PDFs ({len(summary['individual_pdfs'])}):")
        for pdf in summary["individual_pdfs"]:
            logger.info(f"   {pdf['name']:<40} {pdf['size_kb']:>8.1f} KB")

    if summary["web_outputs"]:
        logger.info(f"\n🌐 Web Outputs ({len(summary['web_outputs'])}):")
        for web in summary["web_outputs"]:
            logger.info(f"   {web['name']:<40} {web['size_kb']:>8.1f} KB")

    if summary["slides"]:
        logger.info(f"\n📊 Presentation Slides ({len(summary['slides'])}):")
        for slide in summary["slides"]:
            logger.info(f"   {slide['name']:<40} {slide['size_kb']:>8.1f} KB")

    logger.info(f"\n📦 Total Output Size: {summary['total_size_kb']:.1f} KB ({summary['total_size_kb'] / 1024:.2f} MB)")
    logger.info("=" * BANNER_WIDTH + "\n")


def _check_citations_used(manuscript_dir: Path) -> bool:
    """Check if any manuscript files contain citation commands."""
    citation_patterns = [
        r"\\cite\{[^}]+\}",
        r"\\citep\{[^}]+\}",
        r"\\citet\{[^}]+\}",
        r"\\citeauthor\{[^}]+\}",
        r"\\citeyear\{[^}]+\}",
        r"(?<![A-Za-z0-9_])@(?!(?:fig|tbl|sec|eq):)[A-Za-z0-9_][A-Za-z0-9_:.#$%&+?<>~/-]*",
    ]

    manuscript_files = list(manuscript_dir.glob("*.md"))
    supplemental_dir = manuscript_dir / "supplemental"
    if supplemental_dir.exists():
        manuscript_files.extend(list(supplemental_dir.glob("*.md")))

    for md_file in manuscript_files:
        try:
            content = md_file.read_text(encoding="utf-8")
            for pattern in citation_patterns:
                if re.search(pattern, content):
                    return True
        except (OSError, UnicodeDecodeError) as e:
            logger.debug(f"Could not read {md_file}: {e}")
            continue
    return False


def _rendering_config_for_verify(project_root: Path) -> RenderingConfig:
    """Load the same effective format toggles used by the render orchestrator."""

    manuscript_dir = _manuscript_dir_for_verify(project_root)
    config_path = manuscript_dir / "config.yaml"
    project_config: dict[str, Any] | None = None
    if config_path.is_file():
        try:
            loaded = yaml.safe_load(config_path.read_text(encoding="utf-8"))
        except (OSError, yaml.YAMLError) as exc:
            raise ValueError(f"Could not read rendering configuration {config_path}: {exc}") from exc
        if loaded is not None and not isinstance(loaded, dict):
            raise ValueError(f"Rendering configuration must be a mapping: {config_path}")
        project_config = loaded
    return RenderingConfig.from_project_config(project_config)


def _verify_combined_html(project_root: Path) -> bool:
    """Require a non-empty standalone combined HTML document."""

    output_path = project_root / "output" / "web" / "index.html"
    try:
        if not output_path.is_file() or output_path.stat().st_size == 0:
            logger.error("Combined HTML output missing or empty: %s", output_path)
            return False
        prefix = output_path.read_text(encoding="utf-8")[:8192].lower()
    except (OSError, UnicodeDecodeError) as exc:
        logger.error("Could not validate combined HTML output %s: %s", output_path, exc)
        return False
    if not re.search(r"(?:<!doctype\s+html\b|<html(?:\s|>))", prefix):
        logger.error("Combined HTML output is not a standalone HTML document: %s", output_path)
        return False
    log_success(f"Combined HTML valid: {output_path.name}", logger)
    return True


def _expected_slide_outputs(project_root: Path) -> list[Path]:
    """Return Beamer deliverables expected from the discovered Markdown inputs."""

    manuscript_dir = _manuscript_dir_for_verify(project_root)
    slides_dir = project_root / "output" / "slides"
    expected: list[Path] = []
    for source_file in discover_manuscript_files(manuscript_dir):
        if source_file.suffix != ".md" or is_transmission_bookend(source_file):
            continue
        try:
            source_text = source_file.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as exc:
            logger.error("Could not inspect slide source %s: %s", source_file, exc)
            return [slides_dir / "__unverifiable_slide_source__.pdf"]
        if "<!-- render:skip-beamer -->" in source_text:
            continue
        expected.append(slides_dir / f"{source_file.stem}_slides.pdf")
    return expected


def _verify_slide_outputs(project_root: Path) -> bool:
    """Validate every Beamer PDF expected from the current manuscript inputs."""

    expected = _expected_slide_outputs(project_root)
    if not expected:
        logger.error("Slides are enabled, but no current manuscript source produces a slide deck")
        return False
    slides_dir = project_root / "output" / "slides"
    expected_reserved = {
        *(path for path in expected),
        *(path.with_suffix(".html") for path in expected),
    }
    actual_reserved = {
        *slides_dir.glob("*_slides.pdf"),
        *slides_dir.glob("*_slides.html"),
    }
    unexpected = sorted(actual_reserved - expected_reserved)
    if unexpected:
        for path in unexpected:
            logger.error("Unexpected slide output has no current manuscript source: %s", path)
        return False
    invalid = [path for path in expected if not path.is_file() or not validate_pdf_structure(path)]
    if invalid:
        for path in invalid:
            logger.error("Slide output missing or structurally invalid: %s", path)
        return False
    logger.info("✅ Slide outputs valid: %d expected deck(s)", len(expected))
    return True


def _verify_docx_output(project_root: Path, project_basename: str) -> bool:
    """Validate one exact DOCX identity across the recursive format tree."""

    output_path = project_root / "output" / "docx" / f"{project_basename}_combined.docx"
    unexpected = sorted(set(output_path.parent.rglob("*_combined.docx")) - {output_path})
    if unexpected:
        for path in unexpected:
            logger.error("Unexpected combined DOCX has no current project identity: %s", path)
        return False
    required_members = {"[Content_Types].xml", "word/document.xml"}
    try:
        with zipfile.ZipFile(output_path) as archive:
            names = set(archive.namelist())
            valid = required_members <= names and archive.testzip() is None
    except (OSError, zipfile.BadZipFile) as exc:
        logger.error("Combined DOCX output missing or invalid (%s): %s", output_path, exc)
        return False
    if not valid:
        logger.error("Combined DOCX output has an invalid package structure: %s", output_path)
        return False
    log_success(f"Combined DOCX valid: {output_path.name}", logger)
    return True


def _verify_epub_output(project_root: Path, project_basename: str) -> bool:
    """Validate one exact EPUB identity across the recursive format tree."""

    output_path = project_root / "output" / "epub" / f"{project_basename}_combined.epub"
    unexpected = sorted(set(output_path.parent.rglob("*_combined.epub")) - {output_path})
    if unexpected:
        for path in unexpected:
            logger.error("Unexpected combined EPUB has no current project identity: %s", path)
        return False
    try:
        with zipfile.ZipFile(output_path) as archive:
            validate_epub_package(archive)
    except (EOFError, KeyError, NotImplementedError, OSError, RuntimeError, ValueError, zipfile.BadZipFile) as exc:
        logger.error("Combined EPUB output missing or invalid (%s): %s", output_path, exc)
        return False
    log_success(f"Combined EPUB valid: {output_path.name}", logger)
    return True


def verify_pdf_outputs(project_name: str = "project", *, repo_root: Path | None = None) -> bool:
    """Verify that PDFs were generated with quality checks."""
    logger.info("Verifying PDF outputs...")

    root = repo_root or Path(__file__).parent.parent.parent
    project_root = resolve_project_root(root, project_name)
    pdf_dir = project_root / "output" / "pdf"
    manuscript_dir = _manuscript_dir_for_verify(project_root)

    if not pdf_dir.exists():
        logger.error("PDF output directory not found")
        return False

    pdf_files = list(pdf_dir.glob("*.pdf"))
    project_basename = Path(project_name).name
    combined_pdf = pdf_dir / f"{project_basename}_combined.pdf"
    unexpected_combined = sorted(set(pdf_dir.glob("*_combined.pdf")) - {combined_pdf})
    if unexpected_combined:
        for path in unexpected_combined:
            logger.error("Unexpected combined PDF has no current project identity: %s", path)
        return False

    if pdf_files:
        log_success(f"Generated {len(pdf_files)} PDF file(s)", logger)

        valid_pdfs = 0
        failed_compilations = []

        for pdf_file in sorted(pdf_files):
            size_mb = pdf_file.stat().st_size / (1024 * 1024)
            size_kb = pdf_file.stat().st_size / 1024

            if size_mb > 0.01:
                valid_pdfs += 1
                marker = "📕" if pdf_file == combined_pdf else "  "
                logger.info(f"  {marker} {pdf_file.name} ({size_mb:.2f} MB) ✓")
            else:
                marker = "📕" if pdf_file == combined_pdf else "  "
                status_msg = f"  {marker} {pdf_file.name}"

                if size_kb < 0.1:
                    status_msg += f" - FAILED COMPILATION ({size_kb:.1f} KB)"
                    failed_compilations.append(pdf_file)
                    log_file = pdf_file.parent / f"{pdf_file.stem}.log"
                    if log_file.exists():
                        status_msg += f" - Check log: {log_file.name}"
                    else:
                        alt_log = pdf_file.parent / f"_{pdf_file.stem}.log"
                        if alt_log.exists():
                            status_msg += f" - Check log: {alt_log.name}"
                    logger.error(status_msg)
                else:
                    status_msg += f" - file too small ({size_kb:.1f} KB)"
                    logger.warning(status_msg)

        bib_paths = sorted(manuscript_dir.glob("*.bib"))
        citations_used = _check_citations_used(manuscript_dir)

        if bib_paths:
            logger.info("\n✅ Manuscript bibliography file(s) found and will be processed")
        elif citations_used:
            logger.warning(
                "\n⚠️  Bibliography file not found "
                "(citations detected in manuscript - bibliography processing will be skipped)"
            )
        else:
            logger.info("\nℹ️  Bibliography file not found (no citations detected in manuscript - this is fine)")

        if failed_compilations:
            logger.error(f"\n❌ {len(failed_compilations)} PDF compilation(s) failed:")
            for pdf_file in failed_compilations:
                logger.error(f"  - {pdf_file.name} (0.0 KB - compilation failed)")

        if combined_pdf.exists():
            size_mb = combined_pdf.stat().st_size / (1024 * 1024)
            if size_mb > 0.01:
                if failed_compilations:
                    logger.warning(
                        "\n⚠️  Combined manuscript PDF generated but "
                        f"{len(failed_compilations)} other PDF(s) failed to compile"
                    )
                else:
                    logger.info("\n✅ Combined manuscript PDF successfully generated!")
                logger.info(f"  File size: {size_mb:.2f} MB")
                logger.info(f"  Valid PDFs: {valid_pdfs}/{len(pdf_files)}")
            else:
                logger.error(f"\n❌ Combined manuscript PDF compilation failed ({size_mb:.3f} MB)")
                return False
        else:
            logger.error("\n❌ Combined manuscript PDF not found")
            return False

        logs_clean = _verify_latex_warning_policy(project_root, manuscript_dir)
        return valid_pdfs > 0 and not failed_compilations and logs_clean
    else:
        logger.error("No PDF files found in output directory")
        return False


def verify_render_outputs(project_name: str = "project", *, repo_root: Path | None = None) -> bool:
    """Verify exactly the publication formats enabled for the current run.

    The legacy PDF override remains a PDF-only contract. Normal render runs use
    the effective YAML/environment toggles and require a current, valid
    deliverable for every enabled format.
    """

    root = repo_root or Path(__file__).parent.parent.parent
    project_root = resolve_project_root(root, project_name)
    if (project_root / "scripts" / "_render_pdf_override.py").is_file():
        return verify_pdf_outputs(project_name, repo_root=root)

    try:
        config = _rendering_config_for_verify(project_root)
    except (OSError, TypeError, ValueError) as exc:
        logger.error("Could not determine enabled render formats: %s", exc)
        return False

    project_basename = Path(project_name).name
    checks: list[tuple[str, bool]] = []
    if config.enable_pdf:
        checks.append(("PDF", verify_pdf_outputs(project_name, repo_root=root)))
    if config.enable_html:
        checks.append(("HTML", _verify_combined_html(project_root)))
    if config.enable_slides:
        slides_valid = _verify_slide_outputs(project_root)
        if not config.enable_pdf:
            slides_valid = slides_valid and _verify_latex_warning_policy(
                project_root,
                _manuscript_dir_for_verify(project_root),
            )
        checks.append(("slides", slides_valid))
    if config.enable_docx:
        checks.append(("DOCX", _verify_docx_output(project_root, project_basename)))
    if config.enable_epub:
        checks.append(("EPUB", _verify_epub_output(project_root, project_basename)))

    if not checks:
        logger.error("No render formats are enabled; there is no deliverable to verify")
        return False

    failed = [name for name, valid in checks if not valid]
    if failed:
        logger.error("Enabled render output verification failed: %s", ", ".join(failed))
        return False
    logger.info("✅ Enabled render outputs verified: %s", ", ".join(name for name, _ in checks))
    return True
